Actualización Angular 9
andes/matriculaciones pull request #131
Opened 2020-10-06 19:10 UTC by condorpiedra

### Requerimiento
Actualiza la versión de Angular.  
Desinstala librerías en desuso.
Actualiza las versión de @andes/plex y @andes/icon

### Funcionalidad desarrollada 

1. 
2. 
3. 

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

2020-10-07 16:34 UTC, palita1991 requested changes
**Pantalla de bienvenida** 
ANTES
![image](https://user-images.githubusercontent.com/30004190/95355272-ba17b100-089b-11eb-9c0f-0ef5b68b7597.png)
AHORA
![image](https://user-images.githubusercontent.com/30004190/95356395-fe578100-089c-11eb-9f59-a1b272ccf56d.png)

**Resumen del paciente - No se visualiza el botón de cerrar**
![image](https://user-images.githubusercontent.com/30004190/95355974-8ab57400-089c-11eb-8a0d-1acc454a71c3.png)

**Formación de grado - No se visualizan los íconos**
![image](https://user-images.githubusercontent.com/30004190/95356109-b0db1400-089c-11eb-9b5e-2a9618e18f87.png)

Sidebar de formacion de grado

**Posgrado - sidebar**
![image](https://user-images.githubusercontent.com/30004190/95360158-627c4400-08a1-11eb-812c-92769014d8dc.png)

![image](https://user-images.githubusercontent.com/30004190/95360072-48dafc80-08a1-11eb-9c8e-822305f495e0.png)


**Cuando inicias sesión, ya no se visualiza el efector a menos que entres algún módulo. y el menú hamburguesa solo trae la opción de cambiar de cambiar de organización, por lo que no te deja ir a otro módulo desde ahí ni tampoco cerrar sesión**
https://www.loom.com/share/6c535fc8af3f495290f9236585fc5bf2

**Hay un carácter que debe haber quedo en el código, se ubica abajo del todo**
![image](https://user-images.githubusercontent.com/30004190/95357296-0fed5880-089e-11eb-95b2-867d5f4f6279.png)

![image](https://user-images.githubusercontent.com/30004190/95357198-f3512080-089d-11eb-96b6-2b0b587c53b3.png)

2020-10-07 17:14 UTC, juuliotero commented
https://www.loom.com/share/35d87179c61748308affb7edc39f1d25

Cuando desde el listado de profesionales se hace click en sumar profesional, no se cierra el sidebar.

2020-10-09 10:59 UTC, JSantarelli commented
Les dejo los iconos faltantes en las acciones de la sección "formación de grado" por si les ayuda.

- **title**="Generar credencial" **icon**="card-account-details"
- **title**="Generar certificado de ética" **icon**="documentos"
- **title**="Editar" **icon**="lapiz"
-  **title**="Imprimir datos del profesional" **icon**='impresora'>
- **(click)=**"showFormacion(i)"**icon**="information-outline"

Muchos iconos faltantes estaban resueltos en el [otro PR ](https://github.com/andes/matriculaciones/pull/130)de este repo.

2020-10-15 19:22 UTC, condorpiedra commented
> **Pantalla de bienvenida**
> ANTES
> ![image](https://user-images.githubusercontent.com/30004190/95355272-ba17b100-089b-11eb-9c0f-0ef5b68b7597.png)
> AHORA
> ![image](https://user-images.githubusercontent.com/30004190/95356395-fe578100-089c-11eb-9f59-a1b272ccf56d.png)
> 
> **Resumen del paciente - No se visualiza el botón de cerrar**
> ![image](https://user-images.githubusercontent.com/30004190/95355974-8ab57400-089c-11eb-8a0d-1acc454a71c3.png)
> 
> **Formación de grado - No se visualizan los íconos**
> ![image](https://user-images.githubusercontent.com/30004190/95356109-b0db1400-089c-11eb-9b5e-2a9618e18f87.png)
> 
> Sidebar de formacion de grado
> 
> **Posgrado - sidebar**
> ![image](https://user-images.githubusercontent.com/30004190/95360158-627c4400-08a1-11eb-812c-92769014d8dc.png)
> 
> ![image](https://user-images.githubusercontent.com/30004190/95360072-48dafc80-08a1-11eb-9c8e-822305f495e0.png)
> 
> **Cuando inicias sesión, ya no se visualiza el efector a menos que entres algún módulo. y el menú hamburguesa solo trae la opción de cambiar de cambiar de organización, por lo que no te deja ir a otro módulo desde ahí ni tampoco cerrar sesión**
> https://www.loom.com/share/6c535fc8af3f495290f9236585fc5bf2
> 
> **Hay un carácter que debe haber quedo en el código, se ubica abajo del todo**
> ![image](https://user-images.githubusercontent.com/30004190/95357296-0fed5880-089e-11eb-95b2-867d5f4f6279.png)
> 
> ![image](https://user-images.githubusercontent.com/30004190/95357198-f3512080-089d-11eb-96b6-2b0b587c53b3.png)

Se realizan los cambios sugeridos

2020-10-15 19:23 UTC, condorpiedra commented
> https://www.loom.com/share/35d87179c61748308affb7edc39f1d25
> 
> Cuando desde el listado de profesionales se hace click en sumar profesional, no se cierra el sidebar.

Este comportamiento se encuentra actualmente en master

2020-10-15 19:33 UTC, condorpiedra commented
> Les dejo los iconos faltantes en las acciones de la sección "formación de grado" por si les ayuda.
> 
> * **title**="Generar credencial" **icon**="card-account-details"
> * **title**="Generar certificado de ética" **icon**="documentos"
> * **title**="Editar" **icon**="lapiz"
> * **title**="Imprimir datos del profesional" **icon**='impresora'>
> * **(click)=**"showFormacion(i)"**icon**="information-outline"
> 
> Muchos iconos faltantes estaban resueltos en el [otro PR ](https://github.com/andes/matriculaciones/pull/130)de este repo.

Se realizan los cambios de íconos, utlizando como referencia el PR referenciado. En el commit https://github.com/andes/matriculaciones/pull/131/commits/fbc7bb85f7db56863895fe6b987f11d4ad287064

2020-10-19 12:42 UTC, JSantarelli approved these changes
Se visualizan los iconos en las diferentes secciones.

2020-10-19 18:31 UTC, palita1991 approved these changes

2020-10-29 17:53 UTC, merged