Adjuntar título profesional
andes/matriculaciones pull request #137
Opened 2020-12-03 14:32 UTC by plammel

### Requerimiento
* URL de la User Story, referencia al issue (#1111) o breve descripcion del requerimiento
https://proyectos.andes.gob.ar/browse/MAT-32
### Funcionalidad desarrollada 

1. Componente para adjuntar título de formación profesional
2. 
3. 

### UserStory llegó a completarse

- [x] Si https://proyectos.andes.gob.ar/browse/MAT-32
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [x] Si https://proyectos.andes.gob.ar/browse/MAT-32
- [ ] No

2020-12-16 16:57 UTC, liquid36 requested changes

2020-12-16 16:57 UTC, liquid36 commented on src/app/shared/components/upload-file.component.ts
> +export class UploadFileComponent {
Un solo detalle, fíjate que es una versión vieja de la componente. Hace unos días subió un cambio que agrega el nombre del modulo.

2020-12-16 17:36 UTC, plammel commented on src/app/shared/components/upload-file.component.ts
> +export class UploadFileComponent {
Actualizado

2020-12-16 17:47 UTC, palita1991 approved these changes

2020-12-18 16:22 UTC, liquid36 commented
USUARIO: mbotta  
BUILD NUMBER: [2938](http://condorpiedra.andes.gob.ar:85/2938/mochawesome.html)
CYPRESS RUN: [2071](https://dashboard.cypress.io/projects/xr7gft/runs/2071/specs)
TEST START: 2020-12-18T16:22:33.267Z
TOTAL: 353
SUCCESS: 353
FAIL: 0
SKIPPED: 0

2021-01-05 15:00 UTC, condorpiedra approved these changes

2021-01-05 15:01 UTC, merged