MATRICULACIONES - Refactor plex en pantallas de renovación y matriculación
andes/matriculaciones pull request #142
Opened 2021-02-02 18:51 UTC by palita1991

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-36
https://proyectos.andes.gob.ar/browse/MAT-43
https://proyectos.andes.gob.ar/browse/MAT-44
https://proyectos.andes.gob.ar/browse/MAT-45

**Espera ACTUALIZACIÓN de PLEX, para que se visualice bien el disabled de los plex-card en la grilla de horarios**

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

2021-02-05 17:40 UTC, JSantarelli requested changes

2021-02-05 17:40 UTC, JSantarelli commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.html
> +        <div class="row">
@palita1991 si incorporamos `<plex-wrapper>` no hay necesidad de utilizar el encolumnado bootstrap. Se recomienda eliminar 'rows' y 'cols'. Los inputs y demás componentes los acomoda el componente envolvente.

2021-02-05 17:40 UTC, JSantarelli commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.html
> +<div class="h-100" *ngIf="profEncontrado.length === 0 && noEncontrado">
Acá se puede prescindir de tantos `<section>` y utilizar la directiva aligned="center" y justify para que los elementos queden centrados en el panel lateral ante una búsqueda sin resultados.
> <div class="h-100" aligned="center" *ngIf="profEncontrado.length === 0 && noEncontrado">
    <section>
        <plex-label titulo="Sin resultados"
                    subtitulo="Revisá que los datos ingresados sean correctos, si no estás registrado dirígete a 'Matricularme por primera vez' en la página de inicio"
                    type="warning" size="lg" direction="column" icon="account-alert">
        </plex-label>
        <plex-button justify="center" type="info" size="sm" routerLink="/requisitosGenerales"
                     label="Matricularme por primera vez">
        </plex-button>
    </section>
</div>

2021-02-05 17:43 UTC, JSantarelli commented on src/app/components/turnos/solicitar-turno.component.ts
> +    foco = 'sidebar';
Si empleamos [[aspect] para el layout-responsive](https://www.andes.gob.ar/plex/doc/components/PlexLayoutComponent.html), el foco estará por defecto en el sidebar a menos que el main ocupe las 12 columnas y el sidebar no proyecte ningún componente en el `<router-outlet>`

2021-02-05 18:42 UTC, palita1991 commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.html
> +        <div class="row">
@JSantarelli  Corregido

2021-02-05 18:43 UTC, palita1991 commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.html
> +<div class="h-100" *ngIf="profEncontrado.length === 0 && noEncontrado">
Corregido

2021-02-05 18:44 UTC, palita1991 commented on src/app/components/turnos/solicitar-turno.component.ts
> +    foco = 'sidebar';
eliminado, debe haber quedado de cuando probamos el otro día

2021-02-11 14:21 UTC, juuliotero requested changes
Cuando vas a solicitar un turno, si seleccionar un horario en una fecha, y después seleccionas otro día en el calendario te limpia la selección del horario pero te permite continuar con el pedido de turno.
Si el profesional continúa con el proceso le otorga un turno a las 00:00 hs.

Pasa tanto en renovación solo matriculación por primera vez.

https://www.loom.com/share/4466417352534b2fbaea6bdf222c43e5

2021-02-11 15:03 UTC, palita1991 commented
> Cuando vas a solicitar un turno, si seleccionar un horario en una fecha, y después seleccionas otro día en el calendario te limpia la selección del horario pero te permite continuar con el pedido de turno.
> Si el profesional continúa con el proceso le otorga un turno a las 00:00 hs.
> 
> 
> https://www.loom.com/share/4466417352534b2fbaea6bdf222c43e5

@juuliotero corregido

2021-02-12 12:51 UTC, martinebucarey requested changes

2021-02-12 12:51 UTC, martinebucarey commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.html
> +        <!-- <label class="form-control-label">&nbsp;</label> -->
este comentario se paso o va a proposito??

2021-02-12 12:51 UTC, martinebucarey commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +  @Input() public profesional: IProfesional = {
chequear este input

2021-02-12 12:51 UTC, martinebucarey commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +
los array diaSemana y meses, creo que no se estan usando

2021-02-12 12:51 UTC, martinebucarey commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +
la librería jsPDF se esta usando?? en el caso que si `import { jsPDF } from 'jspdf';`

2021-02-12 12:51 UTC, martinebucarey commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +
chequear los servicios, varios no están siendo usados.

2021-02-12 12:51 UTC, martinebucarey commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +      // tslint:disable-next-line:max-line-length
esto no vale, palabra de marian ja!

2021-02-12 12:51 UTC, martinebucarey commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +// import { PlexValidator } from 'andes-plex/src/lib/core/validator.service';
comentario

2021-02-12 12:51 UTC, martinebucarey commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +  isSelected(turno: any) {
el parámetro turno no iría en esta función

2021-02-12 12:51 UTC, martinebucarey commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +              });
subscribe vació, el parámetro "turno" era para hacer algo??

2021-02-12 12:51 UTC, martinebucarey commented on src/app/components/turnos/seleccion-turnos/seleccion-turnos.component.ts
> +
Los array no se están usando.

2021-02-12 16:11 UTC, palita1991 commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.html
> +        <!-- <label class="form-control-label">&nbsp;</label> -->
Quedó viejo, ya se borró

2021-02-12 16:12 UTC, palita1991 commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +  @Input() public profesional: IProfesional = {
se saco input que no tenia sentido y dejo el profesional que se utiliza para cuando se buscar el profesional al momento de solicitar el turno

2021-02-12 16:12 UTC, palita1991 commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +
Borrado

2021-02-12 16:13 UTC, palita1991 commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +
Arreglado

2021-02-12 16:13 UTC, palita1991 commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +
Borrado servicios que no estaban siendo usados

2021-02-12 16:13 UTC, palita1991 commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +      // tslint:disable-next-line:max-line-length
Borrado, comentario viejo

2021-02-12 16:14 UTC, palita1991 commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +// import { PlexValidator } from 'andes-plex/src/lib/core/validator.service';
Borrado

2021-02-12 16:14 UTC, palita1991 commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +  isSelected(turno: any) {
Se saco parámetro sin uso

2021-02-12 16:14 UTC, palita1991 commented on src/app/components/turnos/seleccion-profesional/seleccion-profesional.component.ts
> +              });
No hacia nada, eso esta asi  desde antes pero probe sacarlo y funciona todo correcto

2021-02-12 16:15 UTC, palita1991 commented on src/app/components/turnos/seleccion-turnos/seleccion-turnos.component.ts
> +
Borrado, no se estaba utilizando quedo por copy paste del otro componente

2021-02-17 14:18 UTC, martinebucarey approved these changes

2021-02-17 17:02 UTC, juuliotero reviewed
Me deja sacar turno para el 1/02/2021 siendo hoy 17/02/2021, no se si es algo que está bien que permita, o habría que deshabilitar las fechas anteriores al día actual.

2021-02-17 17:17 UTC, palita1991 commented
> Me deja sacar turno para el 1/02/2021 siendo hoy 17/02/2021, no se si es algo que está bien que permita, o habría que deshabilitar las fechas anteriores al día actual.

@juuliotero el funcionamiento actual del calendario es asi, solo se le modifico con css el  diseño. Habria que verlo con alguien para ver si esta así por alguna razón actualmente antes modificarlo.

2021-02-24 14:57 UTC, juuliotero approved these changes

2021-03-03 19:27 UTC, MCele approved these changes

2021-03-05 11:24 UTC, JSantarelli commented on src/app/components/turnos/solicitar-turno-matriculacion.html
> +          Fecha y hora: {{ horarioElegido }}.
Un detalle, quizás pondría 'TURNO' en lugar de 'FECHA Y HORA', o alguna palabra que haga referencia a que es la fecha elegida (y no otra fecha).
![turno](https://user-images.githubusercontent.com/5895886/110109295-fd634680-7d8b-11eb-8c0e-9e379090bb9b.PNG)

2021-03-05 12:10 UTC, palita1991 commented on src/app/components/turnos/solicitar-turno-matriculacion.html
> +          Fecha y hora: {{ horarioElegido }}.
Corregido @JSantarelli

2021-03-06 14:16 UTC, JSantarelli approved these changes

2021-05-07 13:31 UTC, merged