fix(MAT-6) Bug que permite sacar turnos con fecha anterior a la actual
andes/matriculaciones pull request #146
Opened 2021-06-16 11:57 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-6

### Funcionalidad desarrollada 
1. Se soluciono el bug que permitía sacar turnos con fechas menores a la actual, inhabilitando aquellas fechas antiguas para no continuar con la acción de sacar el turno.

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [ ] Si
- [X] No

2021-07-23 14:46 UTC, palita1991 approved these changes
@MarianoCampetella  @condorpiedra  Mientras que la persona que ingrese a solicitar turno tenga buen internet dudo que pase, pero en cuando tenga internet lento va a poder seleccionar un día igual si es rapido para seleccionar. Igual es un caso muy fino pero para tener en cuenta por si luego de subir este cambio llega a suceder.
https://www.loom.com/share/30ca698db7f6479288853339c68c29d7

2021-08-05 15:31 UTC, MCele approved these changes

2021-08-23 12:52 UTC, plammel commented on src/app/components/turnos/nuevo-turno.component.ts
> +    let hoy = new Date(tiempoTranscurrido);
Porqué no usar `let hoy = new Date();` directamente?

2021-08-23 18:20 UTC, MarianoCampetella commented on src/app/components/turnos/nuevo-turno.component.ts
> +    let hoy = new Date(tiempoTranscurrido);
Corregido!

2021-09-01 17:14 UTC, condorpiedra requested changes

2021-09-01 17:14 UTC, condorpiedra commented on src/app/components/turnos/nuevo-turno.component.ts
> +      if (date.getTime() < hoy.getTime() && date.toDateString() !== hoy.toDateString()) {
Se puede utilizar la función de moment isAfter para realizar este tipo de comparaciones

2021-09-02 16:29 UTC, MarianoCampetella commented on src/app/components/turnos/nuevo-turno.component.ts
> +      if (date.getTime() < hoy.getTime() && date.toDateString() !== hoy.toDateString()) {
Corregido!!

2021-09-03 18:35 UTC, condorpiedra approved these changes

2021-09-03 18:35 UTC, merged