fix(MAT-8) Error en consola al generar reporte
andes/matriculaciones pull request #147
Opened 2021-06-18 14:51 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-8

### Funcionalidad desarrollada 
1. Se agregaron condicionales al momento de traer los profesionales para evitar lecturas en números de matriculas que estuvieran en nulo

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [ ] Si
- [X] No

2021-07-12 18:08 UTC, palita1991 requested changes

2021-07-12 18:08 UTC, palita1991 commented on src/app/components/reportes/reportes.html
> +                  <span *ngIf="!profesional.formacionGrado?.matriculado && profesional.ultimaMatricula && profesional.formacionGrado?.profesion?.nombre && profesional.ultimaMatricula?.baja?.motivo"
` <span *ngIf="!profesional.formacionGrado?.matriculado && profesional.ultimaMatricula?.baja?.motivo && profesional.formacionGrado?.profesion?.nombre" class="badge badge-danger">`

2021-08-23 13:59 UTC, plammel requested changes

2021-08-23 13:59 UTC, plammel commented on src/app/components/reportes/reportes.html
> +                  <span *ngIf="!profesional.formacionGrado?.matriculado && profesional.ultimaMatricula?.baja?.motivo && profesional.formacionGrado?.profesion?.nombre"
No veo que exista un cambio de condiciones, solo un reordenamiendo no que no estaría afectando el funcionamiento actual... 
Por lo que puedo leer, es posible que el bug se origine porque la condición `!profesional.formacionGrado?.matriculado`, es verdadera tanto para un profesional con formacionGrado y `matriculacion = false`; cómo para un profesional sin formacionGrado (null o undefined). Pero en este último caso pincharía en la linea 151. (validar y de ser el caso, controlar formacionGrado y matriculado separadamente).
Por otro lado, cuidado con el formateo automático: dificulta la revisión de PR y puede generar conflictos con otras branchs.

2021-09-01 15:59 UTC, condorpiedra commented
Se reemplaza por PR https://github.com/andes/matriculaciones/pull/159

2021-09-01 15:59 UTC, closed without merging