feat(MAT-55): fecha de vencimiento de las especialidades
andes/matriculaciones pull request #148
Opened 2021-07-20 18:38 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-55

### Funcionalidad desarrollada 
1. Se agrego la funcionalidad de mostrar la fecha de Vencimiento de la especialidad (posgrado) permitiendo modificar la misma

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [X] Si https://github.com/andes/api/pull/1478
- [ ] No

2021-07-21 18:02 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4644](http://condorpiedra.andes.gob.ar:85/4644/mochawesome.html)
CYPRESS RUN: [3650](https://dashboard.cypress.io/projects/xr7gft/runs/3650/specs)
TEST START: 2021-07-21T18:02:19.969Z
TOTAL: 400
SUCCESS: 397
FAIL: 2
SKIPPED: 1

2021-07-21 18:38 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4646](http://condorpiedra.andes.gob.ar:85/4646/mochawesome.html)
CYPRESS RUN: [3652](https://dashboard.cypress.io/projects/xr7gft/runs/3652/specs)
TEST START: 2021-07-21T18:38:36.583Z
TOTAL: 400
SUCCESS: 397
FAIL: 2
SKIPPED: 1

2021-07-22 16:17 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4668](http://condorpiedra.andes.gob.ar:85/4668/mochawesome.html)
CYPRESS RUN: [3671](https://dashboard.cypress.io/projects/xr7gft/runs/3671/specs)
TEST START: 2021-07-22T16:16:54.683Z
TOTAL: 359
SUCCESS: 345
FAIL: 13
SKIPPED: 1

2021-07-23 11:29 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4680](http://condorpiedra.andes.gob.ar:85/4680/mochawesome.html)
CYPRESS RUN: [3683](https://dashboard.cypress.io/projects/xr7gft/runs/3683/specs)
TEST START: 2021-07-23T11:29:23.066Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-23 14:05 UTC, palita1991 reviewed
@MarianoCampetella  La funcionalidad es correcta, guarda bien la fecha de vencimiento en la formacion de posgrado. Consulta ahora teniendo en cuenta que esa fecha de vencimiento existe, tiene realcion con el Badge de fecha de alta que esta en el sidebar?
![image](https://user-images.githubusercontent.com/30004190/126793474-5b658f92-6b97-4e09-bf48-138407bdc1d6.png)

2021-07-23 14:07 UTC, palita1991 commented on src/app/components/profesionales/formacionPosgrado/formacion-posgrado.component.ts
> +        // private _siisaSrv: SIISAService,
Dejaste comentada esta linea por algo en especial?

2021-07-27 17:43 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4732](http://condorpiedra.andes.gob.ar:85/4732/mochawesome.html)
CYPRESS RUN: [3729](https://dashboard.cypress.io/projects/xr7gft/runs/3729/specs)
TEST START: 2021-07-27T17:42:50.583Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-27 17:44 UTC, MarianoCampetella commented on src/app/components/profesionales/formacionPosgrado/formacion-posgrado.component.ts
> +        // private _siisaSrv: SIISAService,
Correcciones realizadas!

2021-07-28 16:16 UTC, palita1991 approved these changes

2021-09-14 14:31 UTC, plammel approved these changes

2021-09-28 15:28 UTC, palita1991 requested changes
@MarianoCampetella Arreglar conflictos

2021-09-29 18:37 UTC, condorpiedra commented
Funcionalidad incluida en el PR https://github.com/andes/matriculaciones/pull/152

2021-09-29 18:37 UTC, closed without merging