feat(MAT): capturar error cuando turno ya no esta disponible
andes/matriculaciones pull request #149
Opened 2021-07-22 14:03 UTC by palita1991

### Requerimiento
* URL de la User Story, referencia al issue (#1111) o breve descripcion del requerimiento
https://proyectos.andes.gob.ar/browse/MAT-52

### Funcionalidad desarrollada 

1. Al momento que el profesional se matricula por primera vez o quiere renovar matricula se verifica si el turno seleccionado se encuentra disponible

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [x] Si https://github.com/andes/api/pull/1379
- [ ] No

2021-07-26 15:24 UTC, MCele approved these changes

2021-08-06 14:20 UTC, liquid36 requested changes

2021-08-06 14:20 UTC, liquid36 commented on src/app/components/turnos/solicitar-turno-matriculacion.component.ts
> +      const pdf = this._pdfUtils.comprobanteTurno(turno);
Faltaría un 
```
if (turno) {
   ....
}
```

poruqe aunque este el navigate, el subscribe se ejecuta igual.

2021-08-10 11:14 UTC, palita1991 commented on src/app/components/turnos/solicitar-turno-matriculacion.component.ts
> +      const pdf = this._pdfUtils.comprobanteTurno(turno);
Corregido @liquid36

2021-08-25 15:42 UTC, plammel approved these changes

2021-09-07 12:55 UTC, merged