refactor(MAT-56): modificar resultados de busqueda
andes/matriculaciones pull request #150
Opened 2021-07-22 15:50 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-56

### Funcionalidad desarrollada 

1. En guía profesional se modificó la ultima opción de búsqueda para poder buscar a un profesional por: nombre, apellido y por profesión.

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [ ] Si
- [X] No

2021-07-22 16:03 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4667](http://condorpiedra.andes.gob.ar:85/4667/mochawesome.html)
CYPRESS RUN: [3670](https://dashboard.cypress.io/projects/xr7gft/runs/3670/specs)
TEST START: 2021-07-22T16:03:09.251Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-23 14:35 UTC, palita1991 requested changes
Muy bien que arreglaste los **placeholder** . Ahora me pasa que cuando filtro por dni me aparecen los profesionales, pero en los demas filtros no, dejo capturas de las diferentes búsquedas
![image](https://user-images.githubusercontent.com/30004190/126797399-62e4f904-3a6c-46ac-86df-dad48fd47b6a.png)
![image](https://user-images.githubusercontent.com/30004190/126797482-492f7fd6-3fff-41dc-8604-d2641432091b.png)
![image](https://user-images.githubusercontent.com/30004190/126797611-afc991b4-745a-4c05-b834-049e9bc576d8.png)

2021-07-26 19:43 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4716](http://condorpiedra.andes.gob.ar:85/4716/mochawesome.html)
CYPRESS RUN: [3715](https://dashboard.cypress.io/projects/xr7gft/runs/3715/specs)
TEST START: 2021-07-26T19:43:30.911Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-07-27 15:51 UTC, palita1991 approved these changes

2021-07-28 14:53 UTC, palita1991 approved these changes

2021-08-06 15:15 UTC, condorpiedra commented
El filtro por profesión debe ser por id y no por nombre

2021-08-09 11:09 UTC, palita1991 commented
> El filtro por profesión debe ser por id y no por nombre
@MarianoCampetella

2021-08-09 11:09 UTC, palita1991 requested changes
@MarianoCampetella revisar comentario de nati

2021-08-09 14:01 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [4833](http://condorpiedra.andes.gob.ar:85/4833/mochawesome.html)
CYPRESS RUN: [3826](https://dashboard.cypress.io/projects/xr7gft/runs/3826/specs)
TEST START: 2021-08-09T14:00:55.116Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-09 14:04 UTC, MarianoCampetella reviewed
Corregido

2021-08-19 18:19 UTC, MCele approved these changes

2021-08-19 18:50 UTC, plammel requested changes

2021-08-19 18:50 UTC, plammel commented on src/app/components/guiaProfesional/guiaProfesional.html
> +                                        <plex-select label="profesion" [(ngModel)]="busqueda.formacionGrado"
```suggestion
                                        <plex-select label="profesión" [(ngModel)]="busqueda.formacionGrado"
```

2021-08-19 18:50 UTC, plammel commented on src/app/components/guiaProfesional/guiaProfesional.html
> +                                                   placeholder="Ingrese un un apellido" [required]="true">
```suggestion
                                                   placeholder="Ingrese un apellido" [required]="true">
```

2021-08-19 18:50 UTC, plammel commented on src/app/components/guiaProfesional/guiaProfesional.html
> +                                        <plex-select label="profesion" [(ngModel)]="busqueda.formacionGrado"
```suggestion
                                        <plex-select label="profesión" [(ngModel)]="busqueda.formacionGrado"
```

2021-08-20 12:58 UTC, MarianoCampetella commented on src/app/components/guiaProfesional/guiaProfesional.html
> +                                        <plex-select label="profesion" [(ngModel)]="busqueda.formacionGrado"
corregido!

2021-08-20 12:59 UTC, MarianoCampetella commented on src/app/components/guiaProfesional/guiaProfesional.html
> +                                                   placeholder="Ingrese un un apellido" [required]="true">
Corregido

2021-08-20 12:59 UTC, MarianoCampetella commented on src/app/components/guiaProfesional/guiaProfesional.html
> +                                        <plex-select label="profesion" [(ngModel)]="busqueda.formacionGrado"
Corregido

2021-08-20 13:24 UTC, plammel approved these changes

2021-08-20 13:28 UTC, plammel commented on src/app/components/guiaProfesional/guiaProfesional.component.ts
>                  this.busqueda['codigoProfesion'] = this.busqueda.formacionGrado.codigo;
Y me parece que esta linea ya no sería necesaria...

2021-08-20 17:14 UTC, MarianoCampetella commented on src/app/components/guiaProfesional/guiaProfesional.component.ts
>                  this.busqueda['codigoProfesion'] = this.busqueda.formacionGrado.codigo;
Corregido!

2021-08-23 14:28 UTC, plammel approved these changes

2021-08-24 16:31 UTC, palita1991 approved these changes

2021-09-01 16:22 UTC, condorpiedra approved these changes

2021-09-01 16:22 UTC, merged