ref(mat): filtro por profesion en listado
andes/matriculaciones pull request #151
Opened 2021-08-04 11:21 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-60

### Funcionalidad desarrollada 

1. Agrega select de profesión
2. Configura tabulaciones a 4 espacios

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1503
- [ ] No

2021-08-04 11:35 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [4795](http://condorpiedra.andes.gob.ar:85/4795/mochawesome.html)
CYPRESS RUN: [3790](https://dashboard.cypress.io/projects/xr7gft/runs/3790/specs)
TEST START: 2021-08-04T11:34:46.610Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-08-05 13:44 UTC, plammel requested changes

2021-08-05 13:44 UTC, plammel commented on src/app/components/profesionales/listar-profesionales.component.ts
> +      profesion: this.value ? this.value.profesion?.nombre : '',
Buscar por id de profesión: https://github.com/andes/api/pull/1503#pullrequestreview-722165176

2021-08-18 13:29 UTC, negro89 commented on src/app/components/profesionales/listar-profesionales.component.ts
> +      profesion: this.value ? this.value.profesion?.nombre : '',
Hecho, ahora se busca por código

2021-08-19 17:58 UTC, MCele approved these changes

2021-08-23 14:24 UTC, plammel requested changes

2021-08-23 14:24 UTC, plammel commented on src/app/components/profesionales/listar-profesionales.html
> +x
```suggestion
```

2021-08-23 14:24 UTC, plammel commented on src/app/components/profesionales/listar-profesionales.html
> +	<plex-layout-main>
Los cambios en este archivo son únicamente de formato, o incluye algún otro cambio? Cuando se haga un cambio tan grande de formateo, por favor indicar en que lineas se incluyen cambios: se hace muy difícil leer el código e identificar los cambios... Es formateo automático?

2021-08-24 16:43 UTC, palita1991 approved these changes

2021-09-08 16:14 UTC, MCele approved these changes

2021-09-08 18:41 UTC, merged