refactor(MAT-62): Reestructuración de solapa de especialidades
andes/matriculaciones pull request #152
Opened 2021-08-17 17:33 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-62

### Funcionalidad desarrollada 
1. Se refactorizó toda la parte de "formación de posgrado" incluyendo los datos basicos del profesional

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [ ] Si
- [X] No

2021-08-24 15:48 UTC, palita1991 requested changes
@MarianoCampetella quizas en esta parte si no vas a tener nombre de las columnas, no seria mejor hacer un plex list en donde cada item tenga los datos de la fecha y los botones de editar y eliminar en caso de editar y solo la fecha cuando no es la edición?. Quizas seria mejor usar ese recurso en este caso en lugar de plex-table
![image](https://user-images.githubusercontent.com/30004190/130648079-7465bb04-f8dd-4343-b3d7-254eea02c67f.png)
![image](https://user-images.githubusercontent.com/30004190/130648128-64d64924-abfc-4b03-9149-87667a65f264.png)

2021-09-15 15:12 UTC, palita1991 requested changes
@MarianoCampetella 

- Si tenes abierto el sidebar y apretas en editar, te queda el sidebar abierto
https://www.loom.com/share/0656c3c732364013842e77406451e0bc

- Esta mal escrita la palabra deshabilitar
![image](https://user-images.githubusercontent.com/30004190/133455275-30c6b011-1a63-4d3e-99b4-7705d69d8c7d.png)

- Dejar `public columnasFechas = [];` para que no se vea un cuadrado sin titulo
![image](https://user-images.githubusercontent.com/30004190/133456552-b598ddb5-4e67-4ea1-b7ae-840bd9d10d63.png)

- Al agregar un nuevo posgrado no se visualiza en el listado de inmediato, tengo que salir de la edición del profesional y ahí recién la visualizo en el listado. dejo video
https://www.loom.com/share/fa7f1415c7ff45a3956070e58635543c

2021-09-17 18:28 UTC, palita1991 approved these changes

2021-09-21 14:15 UTC, juuliotero requested changes
Si tengo abierto el sidebar de otra solapa, no me la cierra cuando voy a posgrado
https://www.loom.com/share/adb16cfdb87c4bf1bdb94efa4f599911

2021-09-22 12:31 UTC, MarianoCampetella commented on src/app/components/profesionales/detalle-profesional.component.ts
> +    this._profesionalService.patchProfesional(this.profesional.id, cambio).subscribe((profesionalSaved) => {
Corregido!!

2021-09-22 18:56 UTC, MCele approved these changes

2021-09-23 18:58 UTC, merged