refactor(MAT-64): certificado de ética
andes/matriculaciones pull request #154
Opened 2021-08-18 14:51 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-64

### Funcionalidad desarrollada 
1. Se verifica que los certificados de ética se puedan emitir cuando las matriculas con el titulo de grado y especialidad están vigentes. 
2. Se agrego el badge de año de gracia cuando la fecha de vencimiento de la matricula es mayor a la fecha actual pero dentro del rango de los 365 días.

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [ ] Si
- [X] No

2021-09-01 14:08 UTC, condorpiedra requested changes

2021-09-01 14:08 UTC, condorpiedra commented on src/app/components/profesionales/formacionGrado/formacion-grado.html
> +                         *ngIf='formacionGrado.matriculacion.length && formacionGrado.matriculado &&
Evitar colocar condiciones tan largas y complejas en el html.  Se puede utilizar un flag y realizar las comparaciones dentro del componente

2021-09-02 15:41 UTC, MarianoCampetella commented on src/app/components/profesionales/formacionGrado/formacion-grado.html
> +                         *ngIf='formacionGrado.matriculacion.length && formacionGrado.matriculado &&
Corregido!!

2021-09-09 18:40 UTC, condorpiedra requested changes

2021-09-09 18:40 UTC, condorpiedra commented on src/app/components/profesionales/formacionGrado/formacion-grado.component.ts
> +  verificarBadgeVencido(i) {
utilizaría una sola función que haga referencia al vencimiento de una matrícula, podría ser un flag matriculaVencida.  Evitar colocar en las funciones nombres de elementos del html como badge

2021-09-09 18:50 UTC, MCele approved these changes

2021-09-10 12:58 UTC, MarianoCampetella commented on src/app/components/profesionales/formacionGrado/formacion-grado.component.ts
> +  verificarBadgeVencido(i) {
Corregido!

2021-09-10 16:36 UTC, condorpiedra approved these changes

2021-09-10 16:46 UTC, merged