MAT - refactorización de la pantalla principal de profesionales
andes/matriculaciones pull request #158
Opened 2021-08-27 18:38 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-65

### Funcionalidad desarrollada 
1. Se refactorizó la pantalla principal de los profesionales.

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [ ] Si
- [X] No

2021-09-28 16:00 UTC, palita1991 requested changes
@MarianoCampetella 

- Nose si serán los datos pero no estaria demás verificar porque para algunos profesionales como en el video hay tres profesiones que te las repite en el listado.
- Después a modo de consulta, no se si esta hablado con ui/ux @JSantarelli  . Pero cuando se selecciona un profesional pierdo la manera de ir a ver los datos de las formaciones, notas, firmas y demás, ya que el único acceso para ir a esa pantalla es seleccionando el ojito. Quizas propongo poner un botón en el sidebar que me deje ir a esa pantalla o que se siga viendo el ojo.
- En la tabla nose si se podrá dejar funcionando para que te ordene las columnas cuando le haces click, como para completar la funcionalidad completa del plex-table

https://www.loom.com/share/dae698abcc754a46bf721c26b2918148

2021-11-10 14:07 UTC, palita1991 commented on src/app/components/profesionales/listar-profesionales.html
> +        </div>
En el plex-title y plex-button no hace falta la condición ya que esta en el div

2021-11-10 14:15 UTC, palita1991 requested changes
Borrar código comentado de los archivos
- profesional.component.ts
- seleccion-profesional.component.ts
- IProfesional.ts

2021-11-10 14:15 UTC, palita1991 commented on src/app/components/profesionales/listar-profesionales-detalle.html
> +<plex-box type="invert">
No hace falta este plex-box ya que en listar-profesionales.html esta el plex-layout-sidebar en invert

2021-11-10 14:18 UTC, palita1991 requested changes

2021-11-10 14:18 UTC, palita1991 commented on src/app/components/profesionales/listar-profesionales-detalle.html
> +    <plex-label *ngIf="profesional.notas">{{profesional.notas[0]}}</plex-label>
Cuando no tenga notas, pondría un mensajito como el que esta en listado de vacunación para que no quede el plex-title solo, el <br> para mi esta de más pero  eso te lo dejo a tu criterio

2021-11-10 14:18 UTC, palita1991 commented on src/app/components/profesionales/listar-profesionales.html
> +                <plex-title titulo="Buscar profesional" size="lg">
Sacar header y solo dejar div

2021-11-10 14:18 UTC, palita1991 commented on src/app/components/profesionales/listar-profesionales.html
> +            </app-listar-profesionales-detalle>
La condición podria estar directamente en el app-listar-profesionales-detalle
```suggestion
            <app-listar-profesionales-detalle *ngIf='seleccionado' [profesionalSeleccionado]="profesionalSeleccionado"
                                              (cancelar)="cancelarDetalle($event)"
                                              (editarSidebar)="editarProfesional($event)"
                                              [idProfesional]="profesionalSeleccionado.id">
            </app-listar-profesionales-detalle>
```

2021-11-10 14:23 UTC, palita1991 commented on angular.json
> +    "analytics": false
esto lo subiste sin querer verdad?

2021-11-10 18:34 UTC, palita1991 approved these changes

2021-11-17 13:44 UTC, MCele approved these changes

2021-11-17 13:54 UTC, merged