MAT: refactor guía profesional
andes/matriculaciones pull request #165
Opened 2021-09-24 15:21 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-39

### Funcionalidad desarrollada 

1. Refactor visual de pantalla Guía Profesional

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

2021-09-28 17:38 UTC, plammel approved these changes

2021-09-29 18:43 UTC, palita1991 approved these changes

2021-09-30 18:49 UTC, MCele reviewed
El listado no refresca luego de hacer más de una búsqueda y va sumando los profesionales al final de la lista.

2021-10-01 11:37 UTC, palita1991 commented
> El listado no refresca luego de hacer más de una búsqueda y va sumando los profesionales al final de la lista.

Efectivamente se van se van encolando las búsuquedas

2021-10-01 11:40 UTC, palita1991 requested changes
@juuliotero  
https://www.loom.com/share/f3ab073453b64c45bb191b8c74e9c93b

2021-10-01 17:39 UTC, juuliotero commented
> > El listado no refresca luego de hacer más de una búsqueda y va sumando los profesionales al final de la lista.
> 
> @juuliotero Efectivamente se van se van encolando las búsquedas

esto pasa en producción, no se si 

> @juuliotero https://www.loom.com/share/f3ab073453b64c45bb191b8c74e9c93b

corregido

2021-10-01 17:45 UTC, waltergarrido approved these changes

2021-10-01 18:02 UTC, palita1991 approved these changes

2021-10-04 10:57 UTC, merged