feat(MAT-75): Edicion de obtencion de matriculas de posgrado
andes/matriculaciones pull request #166
Opened 2021-09-30 17:01 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-75

### Funcionalidad desarrollada 

1. Se agrego la funcionalidad de editar la solapa "obtencion de matricula"

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [ ] Si
- [X] No

2021-10-01 17:02 UTC, palita1991 approved these changes

2021-11-15 18:19 UTC, juuliotero commented
Rebasear con master @MarianoCampetella. Revisar titulo del PR, debería ser **MAT: Edición de obtención de matriculas de posgrado**

2021-11-15 18:32 UTC, juuliotero requested changes

2021-11-15 18:32 UTC, juuliotero commented on src/app/components/profesionales/formacionPosgrado/formacion-posgrado-detalle.component.ts
>          private _numeracionesService: NumeracionMatriculasService, public auth: Auth) {
_numeracionesService no se usa

2021-11-15 18:32 UTC, juuliotero commented on src/app/components/profesionales/formacionPosgrado/formacion-posgrado-detalle.html
>    <br>
evitar el uso de <br> para separar elementos

2021-11-17 16:37 UTC, MCele approved these changes

2021-11-17 17:17 UTC, juuliotero approved these changes

2021-11-17 17:28 UTC, merged