MAT: guardar filtros en búsquedas de profesionales
andes/matriculaciones pull request #167
Opened 2021-10-01 14:36 UTC by juuliotero

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-73

### Funcionalidad desarrollada 
1. Se crea componente para filtros de listar-profesionales

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

2021-10-01 14:59 UTC, martinebucarey commented
Te rompio el lint, antes de subir hacete un npm run lint -- --fix

2021-10-01 17:52 UTC, juuliotero commented
> Te rompio el lint, antes de subir hacete un npm run lint -- --fix

lisssto

2021-10-05 12:44 UTC, palita1991 requested changes
@juuliotero 
Los filtros de **N° de matrícula grado** y **N° matrícula Especialidad** no filtran

2021-10-06 13:22 UTC, juuliotero commented
> @juuliotero Los filtros de **N° de matrícula grado** y **N° matrícula Especialidad** no filtran

corregido

2021-10-06 18:04 UTC, palita1991 approved these changes

2021-11-17 13:19 UTC, negro89 approved these changes
seselente

2021-11-17 13:19 UTC, negro89 commented on src/app/components/profesionales/services/busqueda-profesional.service.ts
> +import { auditTime, map, switchMap } from 'rxjs/operators';
import auditTime

2021-11-17 13:19 UTC, negro89 commented on src/app/components/profesionales/listar-profesionales.component.ts
>  import 'rxjs/add/operator/switchMap';
import en desuso

2021-11-17 17:44 UTC, MCele approved these changes

2021-11-17 18:17 UTC, merged