Permitir adjuntar y eliminar archivos relacionados con el profesional
andes/matriculaciones pull request #170
Opened 2021-10-14 14:43 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-31

### Funcionalidad desarrollada 
1. Se agrego una nueva funcionalidad donde el profesional va a poder cargar y eliminar los documentos que sean necesarios (titulos de grado, titulos de posgrado y certificados)

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [X] Si https://github.com/andes/api/pull/1580
- [ ] No

2021-10-14 16:59 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5304](http://condorpiedra.andes.gob.ar:85/5304/mochawesome.html)
CYPRESS RUN: [4249](https://dashboard.cypress.io/projects/xr7gft/runs/4249/specs)
TEST START: 2021-10-14T16:58:44.227Z
TOTAL: 357
SUCCESS: 344
FAIL: 12
SKIPPED: 1

2021-10-14 17:15 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5305](http://condorpiedra.andes.gob.ar:85/5305/mochawesome.html)
CYPRESS RUN: [4250](https://dashboard.cypress.io/projects/xr7gft/runs/4250/specs)
TEST START: 2021-10-14T17:15:26.009Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2021-10-18 17:22 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5324](http://condorpiedra.andes.gob.ar:85/5324/mochawesome.html)
CYPRESS RUN: [4269](https://dashboard.cypress.io/projects/xr7gft/runs/4269/specs)
TEST START: 2021-10-18T17:13:34.288Z
TOTAL: 392
SUCCESS: 384
FAIL: 7
SKIPPED: 1

2021-10-19 11:57 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5330](http://condorpiedra.andes.gob.ar:85/5330/mochawesome.html)
CYPRESS RUN: [4275](https://dashboard.cypress.io/projects/xr7gft/runs/4275/specs)
TEST START: 2021-10-19T11:57:15.095Z
TOTAL: 404
SUCCESS: 402
FAIL: 1
SKIPPED: 1

2021-11-16 01:10 UTC, juuliotero requested changes

2021-11-16 01:10 UTC, juuliotero commented on src/app/components/profesionales/documentos/documentos-profesional.html
> +<!-- <div *ngIf="!addDocumento && !verificarArreglos()" justify="center" class="mt-4">
No dejar código comentado

2021-11-16 01:10 UTC, juuliotero commented on src/app/interfaces/IProfesional.ts
> +        tituloFileId?: String;
Este atributo está dos veces (linea 82 y linea 116)

2021-11-16 01:10 UTC, juuliotero commented on src/app/interfaces/IProfesional.ts
> +        tipo: string;
Usar String en lugar de string

2021-11-18 15:52 UTC, MCele approved these changes

2021-11-18 16:47 UTC, juuliotero approved these changes

2021-11-18 17:46 UTC, merged