Actualizacion del html del componente: Supervisor
andes/matriculaciones pull request #171
Opened 2021-10-19 14:53 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-40

### Funcionalidad desarrollada 
1. Se actualizo el HTML del componente de supervisor cambiando los componentes segun correspondia.

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [ ] Si
- [X] No

2021-11-01 16:30 UTC, palita1991 approved these changes

2021-11-15 17:37 UTC, juuliotero requested changes
![image](https://user-images.githubusercontent.com/7090371/141828185-d11dc97d-cc1b-465f-9956-0737f9b6e0f9.png)

El title de firma debería ser del mismo tamaño o más chico que el title del sidebar

2021-11-15 17:45 UTC, juuliotero commented
https://www.loom.com/share/fded8a5f4ece46bc9d96b3b8dc8aa8df

Cuando selecciono un supervisor y cargo un archivo de firma, si no guardo y me voy a otro, sigue mostrando el botón de guardar.
Si guardo me deja la firma que había elegido con el primer supervisor. 

Limpiar el archivo cargado para la firma al cambiar el supervisor seleccionado.

2021-11-15 18:07 UTC, juuliotero requested changes

2021-11-15 18:07 UTC, juuliotero commented on src/app/components/supervisor/listado-supervisores.html
> +    <div *ngIf="!mostrarMensaje" justify="center" class="h-75">
en lugar de usar la variable mostrarMensaje, se podría preguntar por !user, ya que cuando textoLibre es vacío setea users en null.

<div *ngIf="!users" justify="center" class="h-75">

2021-11-15 18:07 UTC, juuliotero commented on src/app/components/supervisor/listado-supervisores.component.ts
>              // const p = organizaciones.permisos.find(x => x === 'matriculaciones:supervisor:aprobar');
eliminar código comentado

2021-11-15 18:07 UTC, juuliotero commented on src/app/components/supervisor/listado-supervisores.component.ts
>      @HostBinding('class.plex-layout') layout = true; // Permite el uso de flex-box en el componente
eliminar esta línea

2021-11-18 15:15 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5500](http://condorpiedra.andes.gob.ar:85/5500/mochawesome.html)
CYPRESS RUN: [4435](https://dashboard.cypress.io/projects/xr7gft/runs/4435/specs)
TEST START: 2021-11-18T15:05:38.839Z
TOTAL: 257
SUCCESS: 229
FAIL: 27
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2021-11-18 15:27 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5501](http://condorpiedra.andes.gob.ar:85/5501/mochawesome.html)
CYPRESS RUN: [4436](https://dashboard.cypress.io/projects/xr7gft/runs/4436/specs)
TEST START: 2021-11-18T15:27:03.993Z
TOTAL: 400
SUCCESS: 399
FAIL: 0
SKIPPED: 1

2021-11-18 19:25 UTC, MCele approved these changes

2021-11-19 13:58 UTC, juuliotero approved these changes

2021-11-19 14:00 UTC, merged