ref(mat): filtros para renovacion de matriculas
andes/matriculaciones pull request #172
Opened 2021-10-21 14:23 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-81

### Funcionalidad desarrollada 

Hay funcionalidad basada en el relevamiento hecho el 14/10
1. Pantalla profesional: Se elimina segundo nivel de filtros y se reemplaza por los de búsqueda de profesionales en proceso de renovación en distintas zonas sanitarias. Se agrega bool para visualizar este segundo nivel.
2. Pantalla reportes: Se agrega filtro por estado de matriculas.
3. Borra código comentado.
4. Elimina sidebar duplicado en template de detalle-profesional (Otras modificaciones son de formato).
5. Reemplaza titulo de 'mantener nro matricula' por 'aprobar matricula' y propiedad 'title' de buttons por 'tooltip' (Otras modificaciones son de formato)
6. Agrega servicio para recurso de zona sanitaria

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si  https://github.com/andes/api/pull/1588
- [ ] No

2021-11-01 18:35 UTC, palita1991 requested changes
@negro89 Todo muy bien los cambios. Solo un detalle para seguir con lo que decia la user, que solo los supervisores van poder filtrar los profesionales que se encuentran en ese estado, actualizados en un rango de fechas y zona sanitaria para permitir la auditoría y la impresión de la credencial de dichos profesionales, entonces me saque dicho permiso desde el gestor y puedo seguir haciendo las mismas acciones que cuando lo tenia.

2021-11-02 15:01 UTC, palita1991 approved these changes

2021-11-24 15:38 UTC, juuliotero approved these changes

2021-12-28 12:21 UTC, martinebucarey requested changes
- El profesional que seleccione no me lo marca como se pide en el mockup no se si eso esta bien o no de todas formas.
- Al entrar a ver un profesional y volver, me borra los filtros y vuelve a dejar el bool desactivado, eso me parece que no es muy como para el usuario

https://www.loom.com/share/8b591521ad6f49cf89adb8fcd8a7ea73

2021-12-28 12:56 UTC, MCele commented
se observa un error al utilizar la "x" del plex-select en el listado de zonas sanitarias

https://www.loom.com/share/ab823526ba874a2fb946c6e8bbc88113

2021-12-28 14:45 UTC, negro89 commented
@martinebucarey 
1. A que mockup te referis?
2. Se agregó funcionalidad

@MCele No pude reproducir el error

2021-12-28 18:13 UTC, martinebucarey commented
> @martinebucarey
> 
>     1. A que mockup te referis?
> 
>     2. Se agregó funcionalidad
> 
> 
> @MCele No pude reproducir el error

Este mock, el badge de papeles sin verificar, en el ejemplo del video aparece el badge de matricula vencida
![imagen](https://user-images.githubusercontent.com/56874534/147594875-ba064343-a5c2-4845-89ec-721ff7c02be9.png)

2022-01-03 16:42 UTC, MCele approved these changes

2022-01-03 17:09 UTC, negro89 commented
> Este mock, el badge de papeles sin verificar, en el ejemplo del video aparece el badge de matricula vencida ![imagen](https://user-images.githubusercontent.com/56874534/147594875-ba064343-a5c2-4845-89ec-721ff7c02be9.png)

Eso es poruque la matrícula esta suspendida. Es una restricción mas fuerte. Esta bien como lo ves.

2022-01-03 17:22 UTC, martinebucarey approved these changes

2022-01-03 17:22 UTC, merged