refactor(MAT-17): Analisis de rutas utilizadas
andes/matriculaciones pull request #173
Opened 2021-11-26 13:50 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-17

### Funcionalidad desarrollada 
1. Se eliminaron las rutas que no se están utilizando

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [X] Si   https://github.com/andes/api/pull/1620
- [ ] No

2021-11-26 14:04 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5531](http://condorpiedra.andes.gob.ar:85/5531/mochawesome.html)
CYPRESS RUN: [4466](https://dashboard.cypress.io/projects/xr7gft/runs/4466/specs)
TEST START: 2021-11-26T14:04:07.018Z
TOTAL: 402
SUCCESS: 401
FAIL: 0
SKIPPED: 1

2021-11-29 14:55 UTC, juuliotero requested changes

2021-11-29 14:55 UTC, juuliotero commented on src/app/services/turno.service.ts
> +    // getTurnosRenovacion(fecha: Date, searchParams: any): Observable<any[]> { // NO SE USA
Si las rutas  ya no se usan, habría que borrar el código. Evitar dejarlo comentado.

2021-12-21 02:54 UTC, MCele approved these changes

2021-12-21 11:22 UTC, liquid36 approved these changes

2021-12-27 12:35 UTC, merged