MAT - Email como dato default a ingresar
andes/matriculaciones pull request #176
Opened 2022-02-09 15:48 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-85

### Funcionalidad desarrollada 

1. Cuando se registra un nuevo profesional, en la parte "datos de contacto" va a figurar por defecto el email
2. Se cambio el icono y la posicion del boton de agregar contacto. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

2022-02-09 17:25 UTC, AgosLizzi reviewed
Campe, una cosita. Cuando voy a editar un profesional y elimino datos, no me deja guardar esas modificaciones. Te podras fijar que pasa ahí? Te adunto el link del video de ejemplo.

https://www.loom.com/share/e87cc9d2f886494f99d25568c8aac5f0

2022-02-09 17:36 UTC, AgosLizzi commented
Dejo otra observación... Cuando voy a editar/cargar datos de un profesional existente que no tiene cargado el email por default, el campo que se agrega es el de teléfono celular. En ese caso me parece oportuno que aparezca el email. Te dejo link con video así lo ves mejor

https://www.loom.com/share/01623907cb554568b3431681a0aec490

2022-02-09 18:27 UTC, MarianoCampetella commented
> Campe, una cosita. Cuando voy a editar un profesional y elimino datos, no me deja guardar esas modificaciones. Te podras fijar que pasa ahí? Te adjunto el link del video de ejemplo.
> 
> https://www.loom.com/share/e87cc9d2f886494f99d25568c8aac5f0

Corregido.

2022-02-09 18:27 UTC, MarianoCampetella commented
> Campe, una cosita. Cuando voy a editar un profesional y elimino datos, no me deja guardar esas modificaciones. Te podras fijar que pasa ahí? Te adjunto el link del video de ejemplo.
> 
> https://www.loom.com/share/e87cc9d2f886494f99d25568c8aac5f0

Corregido!

2022-02-09 18:28 UTC, MarianoCampetella commented
> Dejo otra observación... Cuando voy a editar/cargar datos de un profesional existente que no tiene cargado el email por default, el campo que se agrega es el de teléfono celular. En ese caso me parece oportuno que aparezca el email. Te dejo link con video así lo ves mejor
> 
> https://www.loom.com/share/01623907cb554568b3431681a0aec490

Corregido!

2022-02-15 13:31 UTC, liquid36 commented
USUARIO: lmlagos  
BUILD NUMBER: [5924](http://condorpiedra.andes.gob.ar:85/5924/mochawesome.html)
CYPRESS RUN: [4841](https://dashboard.cypress.io/projects/xr7gft/runs/4841/specs)
TEST START: 2022-02-15T13:25:21.958Z
TOTAL: 354
SUCCESS: 339
FAIL: 14
SKIPPED: 1

2022-02-15 15:04 UTC, liquid36 commented
USUARIO: mcampetella  
BUILD NUMBER: [5929](http://condorpiedra.andes.gob.ar:85/5929/mochawesome.html)
CYPRESS RUN: [4846](https://dashboard.cypress.io/projects/xr7gft/runs/4846/specs)
TEST START: 2022-02-15T15:04:03.330Z
TOTAL: 404
SUCCESS: 403
FAIL: 0
SKIPPED: 1

2022-02-23 11:13 UTC, AgosLizzi approved these changes

2022-02-23 11:52 UTC, palita1991 requested changes
@MarianoCampetella Por alguna razón no se habilita el boton de confirmar datos por lo tanto no te deja editar. Cuando creas un nuevo profesional si se habilita el boton correctamente al completar todos los campos

2022-02-23 15:28 UTC, MarianoCampetella commented
> @MarianoCampetella Por alguna razón no se habilita el boton de confirmar datos por lo tanto no te deja editar. Cuando creas un nuevo profesional si se habilita el boton correctamente al completar todos los campos

Corregido!!

2022-02-25 11:34 UTC, palita1991 approved these changes

2022-07-26 13:49 UTC, MCele approved these changes

2022-07-26 15:28 UTC, merged