MAT - Refactor en el listado de turnos y en el sidebar
andes/matriculaciones pull request #179
Opened 2022-03-02 17:56 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-38

### Funcionalidad desarrollada 
1. Se hizo un refactor en la pantalla principal del listado de turnos y en el sidebar.

### UserStory llegó a completarse
- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos
- [ ] Si
- [X] No

### Requiere actualizaciones en la API
- [ ] Si
- [X] No

2022-03-03 11:41 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6007](http://condorpiedra.andes.gob.ar:85/6007/mochawesome.html)
CYPRESS RUN: [4921](https://dashboard.cypress.io/projects/xr7gft/runs/4921/specs)
TEST START: 2022-03-03T11:40:52.749Z
TOTAL: 388
SUCCESS: 385
FAIL: 2
SKIPPED: 1

2022-03-03 11:50 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6008](http://condorpiedra.andes.gob.ar:85/6008/mochawesome.html)
CYPRESS RUN: [4922](https://dashboard.cypress.io/projects/xr7gft/runs/4922/specs)
TEST START: 2022-03-03T11:50:26.794Z
TOTAL: 393
SUCCESS: 391
FAIL: 1
SKIPPED: 1

2022-03-03 12:02 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6009](http://condorpiedra.andes.gob.ar:85/6009/mochawesome.html)
CYPRESS RUN: [4923](https://dashboard.cypress.io/projects/xr7gft/runs/4923/specs)
TEST START: 2022-03-03T12:01:55.547Z
TOTAL: 401
SUCCESS: 391
FAIL: 10
SKIPPED: 0

2022-03-03 14:37 UTC, palita1991 requested changes
Algunos detalles @MarianoCampetella 

1) El mensaje de bienvenida hay que hacerle scroll para leerlo
https://www.loom.com/share/9e8bc96314b5499ab8abf1143e55fd60

2) Le hice click en el botón de check (Asistió), así se me habilitaba el ojito, una vez habilitado le agregue una nota, volví a la pantalla de turnos y la nota no la veo en el sidebar.

2022-03-04 16:19 UTC, MarianoCampetella commented
> Algunos detalles @MarianoCampetella
> 
> 1. El mensaje de bienvenida hay que hacerle scroll para leerlo
>    https://www.loom.com/share/9e8bc96314b5499ab8abf1143e55fd60
> 2. Le hice click en el botón de check (Asistió), así se me habilitaba el ojito, una vez habilitado le agregue una nota, volví a la pantalla de turnos y la nota no la veo en el sidebar.

Corregido!
Se quito la parte de ver notas ya que todos los datos vienen desde la colección turnosSolicitados y las notas nunca se van a modificar ahí por mas que se le agregue una al profesional.

2022-03-08 12:39 UTC, palita1991 approved these changes

2022-03-08 12:39 UTC, AgosLizzi approved these changes

2022-07-04 14:17 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6767](http://condorpiedra.andes.gob.ar:85/6767/mochawesome.html)
CYPRESS RUN: [5619](https://dashboard.cypress.io/projects/xr7gft/runs/5619/specs)
TEST START: 2022-07-04T14:17:22.904Z
TOTAL: 408
SUCCESS: 404
FAIL: 0
SKIPPED: 4

2022-07-26 14:55 UTC, MCele approved these changes

2022-07-26 15:51 UTC, merged