MAT(Fix) - Se crean profesionales duplicados
andes/matriculaciones pull request #180
Opened 2022-03-07 20:48 UTC by negro89

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-93

### Funcionalidad desarrollada 

1.  Refactor de las funciones de guardado de profesional
2. Se aplica libreria rxjs

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [X] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si https://github.com/andes/api/pull/1670
- [ ] No

2022-03-07 21:02 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6038](http://condorpiedra.andes.gob.ar:85/6038/mochawesome.html)
CYPRESS RUN: [4949](https://dashboard.cypress.io/projects/xr7gft/runs/4949/specs)
TEST START: 2022-03-07T21:01:54.591Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-03-08 11:53 UTC, martinebucarey commented
USUARIO: lmlagos  
BUILD NUMBER: [6040](http://condorpiedra.andes.gob.ar:85/6040/mochawesome.html)
CYPRESS RUN: [4951](https://dashboard.cypress.io/projects/xr7gft/runs/4951/specs)
TEST START: 2022-03-08T11:53:32.209Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-05-11 17:34 UTC, MarianoCampetella commented
> ### Requerimiento
> https://proyectos.andes.gob.ar/browse/MAT-93
> 
> ### Funcionalidad desarrollada
> 1. Refactor de las funciones de guardado de profesional
> 2. Se aplica libreria rxjs
> 
> ### UserStory llegó a completarse
> * [ ]  Si
> * [ ]  No
> * [x]  No corresponde
> 
> ### Requiere actualizaciones en la base de datos
> * [ ]  Si
> * [x]  No
> 
> ### Requiere actualizaciones en la API
> * [x]  Si [MAT(Fix) - Se crean profesionales duplicados api#1670](https://github.com/andes/api/pull/1670)
> * [ ]  No

2022-05-11 18:08 UTC, MarianoCampetella commented
Cuando creo un un profesional desde la app y luego voy a crear el mismo profesional desde matriculaciones, una ves que confirmo los datos y selecciono el botón "cancelar" del plex-modal, ocurre el siguiente problema.
https://www.loom.com/share/000bdefcb9c0425fbc9e5c28a5d87018

2022-07-05 12:58 UTC, MarianoCampetella commented
> > Cuando creo un un profesional desde la app y luego voy a crear el mismo profesional desde matriculaciones, una ves que confirmo los datos y selecciono el botón "cancelar" del plex-modal, ocurre el siguiente problema. https://www.loom.com/share/000bdefcb9c0425fbc9e5c28a5d87018
> 
> corregido!

Me vuelve a salir otro error en consola cuando creo un profesional en la app con el nombre y apellido "test" y creo el mismo profesional desde matriculaciones con el boton "nuevo profesional". No recuerdo si el error anterior era por el apellido.

2022-07-06 15:59 UTC, negro89 commented
@MarianoCampetella creo que ahi quedó.

2022-07-15 15:37 UTC, negro89 commented
@MarianoCampetella corregidooo.

2022-07-22 16:41 UTC, martinebucarey commented
USUARIO: cramos  
BUILD NUMBER: [7088](http://condorpiedra.andes.gob.ar:85/7088/mochawesome.html)
CYPRESS RUN: [5875](https://dashboard.cypress.io/projects/xr7gft/runs/5875/specs)
TEST START: 2022-07-22T16:41:21.968Z
TOTAL: 391
SUCCESS: 389
FAIL: 1
SKIPPED: 1

2022-07-22 16:55 UTC, martinebucarey commented
USUARIO: cramos  
BUILD NUMBER: [7089](http://condorpiedra.andes.gob.ar:85/7089/mochawesome.html)
CYPRESS RUN: [5876](https://dashboard.cypress.io/projects/xr7gft/runs/5876/specs)
TEST START: 2022-07-22T16:55:04.310Z
TOTAL: 409
SUCCESS: 407
FAIL: 1
SKIPPED: 1

2022-07-22 17:39 UTC, martinebucarey commented
USUARIO: cramos  
BUILD NUMBER: [7091](http://condorpiedra.andes.gob.ar:85/7091/mochawesome.html)
CYPRESS RUN: [5878](https://dashboard.cypress.io/projects/xr7gft/runs/5878/specs)
TEST START: 2022-07-22T17:39:03.570Z
TOTAL: 409
SUCCESS: 408
FAIL: 0
SKIPPED: 1

2022-07-25 16:56 UTC, MCele requested changes
Se genera un error en la consola en dos momentos:
1) Al cargar un profesional que ya existe en matriculciones (igual dni y sexo) aparece un modal indicando el problema y si se desea reemplazarlo, si se hace click en cancelar, genera un error el la consola.
Creo que en estos casos debería comportarse como lo hace actualmente en master, si existe avisa que que existe y no permite continuar guardando el profesional.
2) El mismo error ocurre cuando, desde el listado de turnos, se hace click en el botón 
![image](https://user-images.githubusercontent.com/19591224/180860813-8d269107-b9e7-4ed7-b73e-6838620f3ed6.png)
para visualizar el formulario de un profesional que aún no existía en el sistema (sacó el turno para matricularse por primera vez).

2022-07-25 19:23 UTC, MCele requested changes

2022-07-25 19:23 UTC, MCele commented on src/app/components/profesionales/profesional.component.ts
> +                    this.plex.info('info', 'Ya existe un profesional registrado con estos datos, por favor vaya a la seccion "renovacion" para sacar su turno');
Revisar si no falta algún control, ya que no permite sacar un turno cuando el profesional registrado es no matriculado (ejemplo creado desde tm). Debería permitir sacar el turno sin modificar los datos del profesional, hasta que sean verificados (guardado) por un usuario de matriculaciones
![image](https://user-images.githubusercontent.com/19591224/180857308-d6cd3599-7c16-4880-be51-83092e034ac2.png)

2022-08-03 13:13 UTC, MCele approved these changes

2022-08-23 16:01 UTC, AgosLizzi approved these changes

2022-08-30 18:34 UTC, merged