MAT - Registro de profesional: Refactor PLEX
andes/matriculaciones pull request #187
Opened 2022-06-02 13:48 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-37

### Funcionalidad desarrollada 
1. Se refactorizo la pantalla de registro/edición de un profesional agregando componente los siguientes componentes plex: plex-tabs y plex-wrapper.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

2022-06-02 14:15 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6543](http://condorpiedra.andes.gob.ar:85/6543/mochawesome.html)
CYPRESS RUN: [5423](https://dashboard.cypress.io/projects/xr7gft/runs/5423/specs)
TEST START: 2022-06-02T14:14:53.216Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-06-02 14:18 UTC, palita1991 requested changes
@MarianoCampetella 

- Revisar RESPONSIVE en datos de contacto

![image](https://user-images.githubusercontent.com/30004190/171649483-dc441430-32b5-4ddf-a5f7-b46a0329de58.png)

- NO recuerdo si estaba o no el boton de volver en "Nuevo profesional". Pero estaría bueno aprovechar para agregarlo. 

- Aprovechando que estas modificando esta pantalla,  arreglar el sidebar de estadisticas, para que no se pueda expandir tanto cuando se esta creando un profesional

2022-06-02 17:47 UTC, AgosLizzi requested changes
- Intentar que el badge no quede encimado a los botones
![badge](https://user-images.githubusercontent.com/72876985/171693528-b771aa01-4e5b-4650-a081-1e7444b97fc0.JPG)

- Checkbox flotando
![checkbox](https://user-images.githubusercontent.com/72876985/171693707-b328bd07-0594-4617-ac42-657fb3949531.JPG)

- Me sumo al pedido del Botón volver @palita1991 , tener en cuenta que en la versión mobile tenemos el volver del propio dispositivo.

2022-06-07 13:49 UTC, MarianoCampetella commented
> @MarianoCampetella
> 
> * Revisar RESPONSIVE en datos de contacto
> 
> ![image](https://user-images.githubusercontent.com/30004190/171649483-dc441430-32b5-4ddf-a5f7-b46a0329de58.png)
> 
> * NO recuerdo si estaba o no el boton de volver en "Nuevo profesional". Pero estaría bueno aprovechar para agregarlo.
> * Aprovechando que estas modificando esta pantalla,  arreglar el sidebar de estadisticas, para que no se pueda expandir tanto cuando se esta creando un profesional

Corregido! varios de los detalles como el botón volver, el checkbox en el tab de datos de profesión ya están corregidos en otros PRs anteriores.

2022-07-08 16:18 UTC, palita1991 approved these changes

2022-07-11 11:21 UTC, AgosLizzi approved these changes

2022-08-10 17:47 UTC, MCele requested changes
Dejo un detalle de algo más bien visual que noté, hace poco se subió un cambio con los datos de contacto en los que se usa el símbolo "+" para incorporar un nuevo contacto, y por lo que vi en el mockup sugería ese mismo ícono, por ahí se podría dejarlo con ese símbolo para no volver a los íconos anteriores
![image](https://user-images.githubusercontent.com/19591224/183980494-42dac6e2-f660-4878-9e66-97f3d718241b.png)

2022-08-10 18:17 UTC, AgosLizzi commented
Campe, mientras cargaba el formulario me aparecio este error en la consola
![image](https://user-images.githubusercontent.com/72876985/183987056-1547c5bf-cc5e-4c5c-afbd-4c0f2a8386e1.png)

2022-08-11 14:00 UTC, MarianoCampetella commented
> Dejo un detalle de algo más bien visual que noté, hace poco se subió un cambio con los datos de contacto en los que se usa el símbolo "+" para incorporar un nuevo contacto, y por lo que vi en el mockup sugería ese mismo ícono, por ahí se podría dejarlo con ese símbolo para no volver a los íconos anteriores ![image](https://user-images.githubusercontent.com/19591224/183980494-42dac6e2-f660-4878-9e66-97f3d718241b.png)

Corregido! se agregaron los pattern para que los formatos del email y números telefónicos sean los correctos.

2022-08-23 12:42 UTC, AgosLizzi approved these changes

2023-04-25 16:14 UTC, MarianoCampetella commented
Todos los problemas y comentarios de sugerencias fueron agregados y arreglados. 
Se aguardan respuestas de nuevas correcciones.

2023-04-25 16:20 UTC, negro89 approved these changes

2023-04-26 12:16 UTC, MCele approved these changes

2023-04-26 12:21 UTC, merged