MAT - Agendas incorporar componentes PLEX
andes/matriculaciones pull request #188
Opened 2022-06-08 12:53 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-34

### Funcionalidad desarrollada 

1. Se hizo un refactor de la pantalla de agendas agregando componentes plex.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

2022-06-10 18:59 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6594](http://condorpiedra.andes.gob.ar:85/6594/mochawesome.html)
CYPRESS RUN: [5451](https://dashboard.cypress.io/projects/xr7gft/runs/5451/specs)
TEST START: 2022-06-10T18:58:59.345Z
TOTAL: 391
SUCCESS: 380
FAIL: 10
SKIPPED: 1

2022-06-15 13:48 UTC, palita1991 requested changes
@MarianoCampetella Detalles a cambiar

- Los label del listado deberían estar un poco más grandes, size="lg". Y el boton de editar en size="md", y sacarle el class al boton.
- Tamaño de los plex-label de los feriados en el sidebar, con size="md"
- Después hay una mezcla de código en el uso del plex-table, por ejemplo
   - **[columns]="columnasFeriados"** esta tanto en la tabla principal como en el sidebar.
   - Después están <plex-column></plex-column> pero no lo estas usando en ninguna de las 
     dos tablas. Entonces es como que se esta utilizando el componente a medias y se hace 
     una mezcla de código que me gustaría consultar con @martinebucarey .

2022-06-15 14:29 UTC, martinebucarey requested changes

2022-06-30 13:56 UTC, MarianoCampetella commented on src/app/interfaces/IAgendaMatriculaciones.ts
> +    diasHabilitados: any[];
> > @MarianoCampetella Detalles a cambiar
> > ```
> > * Los label del listado deberían estar un poco más grandes, size="lg". Y el boton de editar en size="md", y sacarle el class al boton.
> > 
> > * Tamaño de los plex-label de los feriados en el sidebar, con size="md"
> > 
> > * Después hay una mezcla de código en el uso del plex-table, por ejemplo
> >   
> >   * **[columns]="columnasFeriados"** esta tanto en la tabla principal como en el sidebar.
> >   * Después están  pero no lo estas usando en ninguna de las
> >     dos tablas. Entonces es como que se esta utilizando el componente a medias y se hace
> >     una mezcla de código que me gustaría consultar con @martinebucarey .
> > 
> > * Los botones del sidebar, tiene un **+** pero deberian llevar un **check** o la palabra **guardar**
> > ```
> 
> Si estoy de acuerdo, columnasFeriados es un array vació por lo tanto no tiene ninguna columna, en el html se esta llamando al input [columns] pero con el array vació, no tiene mucho sentido. La mejor solucion me parece es agregar las coolumnas en el array y ahi si llamar al input.

Corregido!

2022-06-30 13:57 UTC, MarianoCampetella commented
> > @MarianoCampetella Detalles a cambiar
> > ```
> > * Los label del listado deberían estar un poco más grandes, size="lg". Y el boton de editar en size="md", y sacarle el class al boton.
> > 
> > * Tamaño de los plex-label de los feriados en el sidebar, con size="md"
> > 
> > * Después hay una mezcla de código en el uso del plex-table, por ejemplo
> >   
> >   * **[columns]="columnasFeriados"** esta tanto en la tabla principal como en el sidebar.
> >   * Después están  pero no lo estas usando en ninguna de las
> >     dos tablas. Entonces es como que se esta utilizando el componente a medias y se hace
> >     una mezcla de código que me gustaría consultar con @martinebucarey .
> > 
> > * Los botones del sidebar, tiene un **+** pero deberian llevar un **check** o la palabra **guardar**
> > ```
> 
> Si estoy de acuerdo, columnasFeriados es un array vació por lo tanto no tiene ninguna columna, en el html se esta llamando al input [columns] pero con el array vació, no tiene mucho sentido. La mejor solucion me parece es agregar las coolumnas en el array y ahi si llamar al input.

Corregido!

2022-07-01 11:46 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6742](http://condorpiedra.andes.gob.ar:85/6742/mochawesome.html)
CYPRESS RUN: [5595](https://dashboard.cypress.io/projects/xr7gft/runs/5595/specs)
TEST START: 2022-07-01T11:46:41.062Z
TOTAL: 408
SUCCESS: 405
FAIL: -1
SKIPPED: 4

2022-07-06 14:18 UTC, MarianoCampetella commented
> Campe, un par de cositas sobre este pr:
> 
> 1. Los días del listado en negro, para que se logré un buen contraste. Y el botón editar, si puede ir más chico, mejor
>    ![image](https://user-images.githubusercontent.com/72876985/177384313-6ef903ff-77ea-4045-9ac8-cc5b53476de5.png)
> 2. El botón "guardar" sobre el plex title de feriados no debería estar con un +. Se debería visualizar de la misma manera que los botones de plex title de arriba "editar agenda"
>    ![image](https://user-images.githubusercontent.com/72876985/177384590-9f35fdf2-6bd9-49fa-9e66-1257a2de5ae4.png)
> 3. Te dejo un video de algo que me parece medio inconsistente. Cuando cambio la hora de inicio y fin de la agenda, como también los minutos automaticamente hace los cambios en el listado. No pasa cuando realizas los cambios sobre los días, hasta dar al botón "guardar". Para estos casos se debe lograr una coherencia, si pasa con uno que pase con todos, y si no es posible lograr que "pase con todos" que ninguno tenga esa función.
>    https://www.loom.com/share/80180097cbae4aa496b4c178753b3b1e

Corregido! Ahora se agrego el detalle de que si se edita y se cierra el sidebar (porque el usuario cancelo los cambios) al momento de volver a editar los datos de la agenda van a estar con los valores por defecto que tiene cargado.

2022-07-07 18:26 UTC, palita1991 requested changes
@MarianoCampetella Muy  buen laburito quedó bueno, solo dos detalles nomás

1. Los <plex-label> del listado ponerlos en size="md", me retracto de mi comentario anterior, en este nuevo diseño quedaba muy tosco el size="lg"
2. El resizable en este caso sacarlo ya que no creo que necesiten agrandar el sidebar.

2022-07-08 11:31 UTC, MarianoCampetella commented
> 2\. El resizable en este caso sacarlo ya que no creo que necesiten agrandar el sidebar.

Corregido, se saco el resizable del sidebar y los label pasaron a tener la medida md.

2022-07-08 16:01 UTC, palita1991 approved these changes

2022-07-11 11:09 UTC, AgosLizzi approved these changes
Ahora sii :-)

2022-07-28 17:24 UTC, MCele approved these changes

2022-07-28 17:50 UTC, merged