MAT - Eliminar opción de dar de baja en una matricula suspendida
andes/matriculaciones pull request #191
Opened 2022-07-01 16:05 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-103

### Funcionalidad desarrollada 

1. Se agrego una condición para que se visualice el dropdown con la opción de dar de baja a una matrícula. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

2022-07-01 17:19 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6757](http://condorpiedra.andes.gob.ar:85/6757/mochawesome.html)
CYPRESS RUN: [5609](https://dashboard.cypress.io/projects/xr7gft/runs/5609/specs)
TEST START: 2022-07-01T17:19:21.468Z
TOTAL: 325
SUCCESS: 302
FAIL: 22
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-07-04 12:33 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6763](http://condorpiedra.andes.gob.ar:85/6763/mochawesome.html)
CYPRESS RUN: [5615](https://dashboard.cypress.io/projects/xr7gft/runs/5615/specs)
TEST START: 2022-07-04T12:29:31.936Z
TOTAL: 173
SUCCESS: 110
FAIL: 62
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-07-04 12:46 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6764](http://condorpiedra.andes.gob.ar:85/6764/mochawesome.html)
CYPRESS RUN: [5616](https://dashboard.cypress.io/projects/xr7gft/runs/5616/specs)
TEST START: 2022-07-04T12:45:50.937Z
TOTAL: 398
SUCCESS: 387
FAIL: 7
SKIPPED: 4

2022-07-04 14:05 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6766](http://condorpiedra.andes.gob.ar:85/6766/mochawesome.html)
CYPRESS RUN: [5618](https://dashboard.cypress.io/projects/xr7gft/runs/5618/specs)
TEST START: 2022-07-04T14:05:13.466Z
TOTAL: 352
SUCCESS: 339
FAIL: 10
SKIPPED: 3

2022-07-05 12:24 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6777](http://condorpiedra.andes.gob.ar:85/6777/mochawesome.html)
CYPRESS RUN: [5629](https://dashboard.cypress.io/projects/xr7gft/runs/5629/specs)
TEST START: 2022-07-05T12:23:42.708Z
TOTAL: 358
SUCCESS: 343
FAIL: 13
SKIPPED: 2

2022-07-05 13:42 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [6778](http://condorpiedra.andes.gob.ar:85/6778/mochawesome.html)
CYPRESS RUN: [5630](https://dashboard.cypress.io/projects/xr7gft/runs/5630/specs)
TEST START: 2022-07-05T13:42:06.276Z
TOTAL: 409
SUCCESS: 405
FAIL: 2
SKIPPED: 2

2022-07-05 16:53 UTC, AgosLizzi requested changes
Campe, según lo que dice la tarea la opción se debe quitar **solo desde el sidebar**, trascribo ... "Debería quitarse esa opción desde la edición en el sidebar (quitar dropdown del sidebar al editar, ya que no es necesario visualizarlo desde ahí)" 

Sobre el listado no me aparece esa opción. 
![Listado](https://user-images.githubusercontent.com/72876985/177378135-0923917f-39c1-4b58-b9db-94f0eba3ecc6.JPG)

2022-07-06 14:11 UTC, MarianoCampetella commented
> Campe, según lo que dice la tarea la opción se debe quitar **solo desde el sidebar**, trascribo ... "Debería quitarse esa opción desde la edición en el sidebar (quitar dropdown del sidebar al editar, ya que no es necesario visualizarlo desde ahí)"
> 
> Sobre el listado no me aparece esa opción. ![Listado](https://user-images.githubusercontent.com/72876985/177378135-0923917f-39c1-4b58-b9db-94f0eba3ecc6.JPG)

Corregido!

2022-07-07 17:57 UTC, palita1991 approved these changes

2022-07-11 11:00 UTC, AgosLizzi requested changes
Campe, el botón editar sobre el listado no tiene acción ...
https://www.loom.com/share/aae726cb1e11405489ee125794a27bfe
Podes revisar eso, por fa?

2022-07-11 11:47 UTC, MarianoCampetella commented
> Campe, el botón editar sobre el listado no tiene acción ... https://www.loom.com/share/aae726cb1e11405489ee125794a27bfe Podes revisar eso, por fa?

Este fix se va a resolver en un nuevo pr https://proyectos.andes.gob.ar/browse/MAT-107 ya que no se pedía para esta tarea!

2022-07-11 11:52 UTC, AgosLizzi approved these changes

2022-07-27 14:07 UTC, MCele approved these changes

2022-07-28 17:13 UTC, merged