MAT - Boton sin funcionamiento en el dropdown del listado de posgrados
andes/matriculaciones pull request #194
Opened 2022-08-03 17:33 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-107

### Funcionalidad desarrollada 

1. Se elimino el botón de editar posgrado que se encontraba en el dropdown del listado de posgrados de un profesional ya que, segun lo charlado, se solapaban las funcionalidades cuando se lo seleccionaba. A demás ya existe un botón editar cuando se visualizan los datos de un posgrado en particular. 

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

2022-08-03 17:53 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7297](http://condorpiedra.andes.gob.ar:85/7297/mochawesome.html)
CYPRESS RUN: [6055](https://dashboard.cypress.io/projects/xr7gft/runs/6055/specs)
TEST START: 2022-08-03T17:53:36.621Z
TOTAL: 117
SUCCESS: 26
FAIL: 91
SKIPPED: 0
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2022-08-03 18:18 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7298](http://condorpiedra.andes.gob.ar:85/7298/mochawesome.html)
CYPRESS RUN: [6056](https://dashboard.cypress.io/projects/xr7gft/runs/6056/specs)
TEST START: 2022-08-03T18:18:03.940Z
TOTAL: 406
SUCCESS: 403
FAIL: 2
SKIPPED: 1

2022-08-03 18:57 UTC, martinebucarey commented
USUARIO: mcampetella  
BUILD NUMBER: [7300](http://condorpiedra.andes.gob.ar:85/7300/mochawesome.html)
CYPRESS RUN: [6058](https://dashboard.cypress.io/projects/xr7gft/runs/6058/specs)
TEST START: 2022-08-03T18:57:34.982Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2022-08-04 17:58 UTC, AgosLizzi requested changes
Campe, vi dos comportamientos raros:

1. Al presionar el botón editar, me desaparecen las "funciones" de **Obtención de matricula y Revalidaciones**. Hay alguna justificación por la cual suceda esto? sabiendo que si quedan a la vista las fechas de alta y notas. Te dejo el video : 
https://www.loom.com/share/d4ce62917284429e855b34a78fc7a64b
2. Cuando estoy editando, y aprieto el botón cancelar, me cierra el sidebar (?). La cruz cierra el sidebar y el cancelar vuelve un paso atras. El funcionamiento correcto del botón cancelar deberia ser que te devuelve a la pantalla de "Detalle de especialidad"
![image](https://user-images.githubusercontent.com/72876985/182918809-75d1ae66-a186-4369-bf63-a6765a047f6c.png)

2022-08-04 19:08 UTC, MCele approved these changes

2022-08-05 11:19 UTC, MarianoCampetella commented
> Campe, vi dos comportamientos raros:
> 
> 1. Al presionar el botón editar, me desaparecen las "funciones" de **Obtención de matricula y Revalidaciones**. Hay alguna justificación por la cual suceda esto? sabiendo que si quedan a la vista las fechas de alta y notas. Te dejo el video :
>    https://www.loom.com/share/d4ce62917284429e855b34a78fc7a64b
> 2. Cuando estoy editando, y aprieto el botón cancelar, me cierra el sidebar (?). La cruz cierra el sidebar y el cancelar vuelve un paso atras. El funcionamiento correcto del botón cancelar deberia ser que te devuelve a la pantalla de "Detalle de especialidad"
>    ![image](https://user-images.githubusercontent.com/72876985/182918809-75d1ae66-a186-4369-bf63-a6765a047f6c.png)

Ambos comportamientos de por si ya estaban funcionando de esa manera antes de que se resuelva el PR. Lo que se puede hacer es crear una nueva tarea en donde se resuelvan todos estos problemas que fueron descriptos arriba, ya que de por si no se pedia para este pr.

2022-08-22 17:43 UTC, AgosLizzi approved these changes

2023-04-26 12:53 UTC, negro89 approved these changes

2023-04-26 14:35 UTC, merged