MOBILE - Configuración de parametros
andes/matriculaciones pull request #198
Opened 2022-09-06 14:31 UTC by palita1991

### Requerimiento
https://proyectos.andes.gob.ar/browse/AM-231

### Funcionalidad desarrollada 

1. Al generarse el QR de la matrícula en la app mobile, te redirige a la url de Guia Profesional, y en caso de que llegue como parametro el documento que complete los filtros

### UserStory llegó a completarse

- [x] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

2023-01-09 18:40 UTC, negro89 approved these changes

2023-01-19 13:21 UTC, MarianoCampetella approved these changes

2023-01-27 17:08 UTC, negro89 approved these changes
De 10! 

Agrego un commit para sacar los filtros cuando viene un documento por parametro.

2023-03-03 18:10 UTC, Fabio-Ramirez commented
Observamos, que al momento de crear una formacion de  grado al profesional sin verificar papeles, resulta que al querer listar la guia de profesionales aparece "sin resultado". A continuacion mostramos la captura de formaciones cargadas para un profesional, y posteriormente la captura de la direccion url derivada del qr. 
![image](https://user-images.githubusercontent.com/45831788/222794364-57dd25e4-2d74-4555-813b-33ee6bb3ba9a.png)

![image](https://user-images.githubusercontent.com/45831788/222794405-81d9170b-e302-44ad-be78-30799dafb980.png)

En la app mobile, ocurre que falla tambien en el mismo caso, de una matricula "sin verificar papeles"
![image](https://user-images.githubusercontent.com/45831788/222795414-c5206d6d-0c6e-4e16-9c13-7205db6ac303.png)

2023-03-07 18:38 UTC, Fabio-Ramirez commented on src/app/components/guiaProfesional/guiaProfesional.html
> +                <plex-badge type="success" *ngIf="profesional.matriculado">MATRÍCULA N°{{profesional.matricula}}
```suggestion
                <plex-badge type="success" *ngIf="profesional.matriculado">MATRÍCULA N°{{profesional.matricula}}
                <plex-badge type="danger" *ngIf="!profesional.matriculado && profesional.matriculacion">MATRÍCULA N°{{profesional.matricula}}
                    VENCIDA</plex-badge>
                    <plex-badge type="danger" *ngIf="!profesional.matriculado && !profesional.matriculacion">
                        NO POSEE MATRICULA</plex-badge>
```

2023-03-07 18:46 UTC, Fabio-Ramirez commented
Requiere ademas cambio en la api, en el caso de que una formacion de grado no tenga matricula la api no devuelve ningun elemento.

2023-03-13 16:13 UTC, negro89 commented
> Observamos, que al momento de crear una formacion de grado al profesional sin verificar papeles, resulta que al querer listar la guia de profesionales aparece "sin resultado". A continuacion mostramos la captura de formaciones cargadas para un profesional, y posteriormente la captura de la direccion url derivada del qr. ![image](https://user-images.githubusercontent.com/45831788/222794364-57dd25e4-2d74-4555-813b-33ee6bb3ba9a.png)
> 
> ![image](https://user-images.githubusercontent.com/45831788/222794405-81d9170b-e302-44ad-be78-30799dafb980.png)
> 
> En la app mobile, ocurre que falla tambien en el mismo caso, de una matricula "sin verificar papeles" ![image](https://user-images.githubusercontent.com/45831788/222795414-c5206d6d-0c6e-4e16-9c13-7205db6ac303.png)

Se fixea este bug en el listado en la mobile.

2023-04-12 15:20 UTC, aldoEMatamala requested changes
Se sugieren cambios detallados en apartado "files changed"  src/app/components/guiaProfesional/guiaProfesional.html

2023-04-28 11:48 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8793](http://condorpiedra.andes.gob.ar:85/8793/mochawesome.html)
CYPRESS RUN: [7963](https://dashboard.cypress.io/projects/xr7gft/runs/7963/specs)
TEST START: 2023-04-28T11:48:11.207Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-04-28 13:01 UTC, aldoEMatamala approved these changes

2023-04-28 13:11 UTC, merged