MAT - Precarga del formulario
andes/matriculaciones pull request #199
Opened 2022-09-13 11:42 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-112

### Funcionalidad desarrollada 

1. Se agrega una condición para verificar si el profesional esta matriculado o no y de esta forma saber si debe obtener los datos de la colección de profesionales o de turno solicitado

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si 
- [X] No

2022-09-13 12:36 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7609](http://condorpiedra.andes.gob.ar:85/7609/mochawesome.html)
CYPRESS RUN: [6454](https://dashboard.cypress.io/projects/xr7gft/runs/6454/specs)
TEST START: 2022-09-13T12:36:41.811Z
TOTAL: 406
SUCCESS: 405
FAIL: 0
SKIPPED: 1

2023-06-15 12:52 UTC, negro89 reviewed
Campe, un par de observaciones:
- Agregaría un par de comentarios con la idea de cada bloque de código para contextualizar un poco
- Trataría de evitar lo mas posible subscribes anidados.

2023-06-15 12:52 UTC, negro89 commented on src/app/components/profesionales/detalle-profesional.component.ts
>                          this.route.params
Guardaría los parámetros de la ruta en una constante la primera vez que se accede para volver a llamar. Quedaría un poco mas limpia esa parte.

2023-06-15 17:01 UTC, ma7payne approved these changes

2023-06-15 17:27 UTC, Fabio-Ramirez requested changes

2023-06-15 17:27 UTC, Fabio-Ramirez commented on src/app/components/profesionales/detalle-profesional.component.ts
> +                        if (this.profesional.profesionalMatriculado === false){
Se podria agregar el negado (!) para observar si el falso o no.

2023-06-21 13:50 UTC, MarianoCampetella commented on src/app/components/profesionales/detalle-profesional.component.ts
>                          this.route.params
Corregido!

2023-06-21 13:50 UTC, MarianoCampetella commented on src/app/components/profesionales/detalle-profesional.component.ts
> +                        if (this.profesional.profesionalMatriculado === false){
Corregido!

2023-06-29 17:25 UTC, negro89 approved these changes

2023-07-03 11:35 UTC, Fabio-Ramirez approved these changes

2023-07-03 11:36 UTC, merged