MAT - Listado de turnos por dia
andes/matriculaciones pull request #200
Opened 2022-09-20 13:47 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-117

### Funcionalidad desarrollada 

1.  Se puede descargar dentro de un PDF el listado de todos los turnos de los profesionales que solicitaron para matricularse o para realizar la renovación de la misma.
2. Se implemento el scroll infinito al momento de traer los resultados de la busqueda.

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [X] Si   https://github.com/andes/api/pull/1759
- [ ] No

2022-09-20 14:06 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [7665](http://condorpiedra.andes.gob.ar:85/7665/mochawesome.html)
CYPRESS RUN: [6596](https://dashboard.cypress.io/projects/xr7gft/runs/6596/specs)
TEST START: 2022-09-20T14:06:43.259Z
TOTAL: 406
SUCCESS: 404
FAIL: 1
SKIPPED: 1

2022-10-19 12:02 UTC, AgosLizzi requested changes
Campe, el único cambio que hay que realizar sería del encabezado. Te detallo a continuación:

- Esta demasiado grande, es decir, esta ocupando todo el ancho de la hoja. Comunmente se les proporciona un margen. Así lo tenes vos:
![image](https://user-images.githubusercontent.com/72876985/196684729-05ed890c-6622-4ca9-8724-083eb67350a7.png)
Te dejo un ejemplo: 
![ejemplo](https://user-images.githubusercontent.com/72876985/196685123-8117ba8a-2f12-44dd-82cc-42f23c6b7579.JPG)

- Por otro lado, no veo muy relevante la marca de los 50 años, ya que pertenece al 2020. EN su lugar incorporaría el logo de Andes, que no lo veo en el conjunto.

2022-10-19 18:15 UTC, MarianoCampetella commented
> Campe, el único cambio que hay que realizar sería del encabezado. Te detallo a continuación:
> 
> * Esta demasiado grande, es decir, esta ocupando todo el ancho de la hoja. Comunmente se les proporciona un margen. Así lo tenes vos:
>   ![image](https://user-images.githubusercontent.com/72876985/196684729-05ed890c-6622-4ca9-8724-083eb67350a7.png)
>   Te dejo un ejemplo:
>   ![ejemplo](https://user-images.githubusercontent.com/72876985/196685123-8117ba8a-2f12-44dd-82cc-42f23c6b7579.JPG)
> * Por otro lado, no veo muy relevante la marca de los 50 años, ya que pertenece al 2020. EN su lugar incorporaría el logo de Andes, que no lo veo en el conjunto.

Corregido! Se cambio y se acomodo la imagen del encabezado.

2022-10-20 17:20 UTC, AgosLizzi approved these changes

2023-04-12 15:17 UTC, aldoEMatamala approved these changes

2023-04-20 17:41 UTC, Fabio-Ramirez requested changes
Se requiere un mini cambio.

2023-04-21 13:17 UTC, MarianoCampetella commented on src/app/components/turnos/turnos.component.ts
> +        fechaHoy: new Date(),
Corregido!

2023-04-27 13:34 UTC, Fabio-Ramirez approved these changes

2023-06-22 15:14 UTC, negro89 commented on src/app/components/turnos/turnos.component.ts
> +            this.pdfService.listadoTurnos(filtrosPDF, 'listadoTurnos').subscribe();
Recordemos que no es una buena práctica anidar subscribes!

2023-06-22 18:30 UTC, MarianoCampetella commented on src/app/components/turnos/turnos.component.ts
> +                    if (val === 'documento') {
Corregido!!

2023-06-22 18:31 UTC, MarianoCampetella commented on src/app/components/turnos/turnos.component.ts
> +            this.pdfService.listadoTurnos(filtrosPDF, 'listadoTurnos').subscribe();
Corregido! ya no están mas anidados

2023-07-03 11:53 UTC, merged