MAT-124 - Modificar profesion
andes/matriculaciones pull request #203
Opened 2023-02-17 17:22 UTC by aldoEMatamala

### Requerimiento
* URL de la User Story, referencia al issue (#1111) o breve descripcion del requerimiento

### Funcionalidad desarrollada 

1. Al editar una formación de grado, se agregó el selector de la profesión si es que la formación de grado cumple con tener "papeles verificados" y no tener ninguna matrícula asignada. Caso contrario estará deshabilitada.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [x] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

![imagen](https://user-images.githubusercontent.com/123381977/219721400-06198da8-f994-421c-a88a-4d813f482c04.png)

2023-03-07 17:31 UTC, MarianoCampetella commented
Al momento de editar una profesión, si elimino el nombre de la misma se rompe todo como se ve en la imagen.
Las clases que generan este tipo de inconveniente son: 
- formacion-grado.html en la linea 107
- formacion-grado-detalle.html en la linea 2
![image](https://user-images.githubusercontent.com/65697028/223484436-42aee0db-95a2-43bb-a7ea-6ed633706011.png)

También ocurre lo siguiente para agregar en la misma corrección:
- Cuando edito una profesión, borro el nombre y apreto el botón cancelar, el grado editado desaparece y vuelve a arrojar múltiples errores en la consola.
![image](https://user-images.githubusercontent.com/65697028/223485477-27bc4fec-26e5-4904-8d01-2fd3d197d26a.png)

-  Cuando edito una profesión, agrego otro nombre y apreto el botón cancelar, el grado editado queda con la nueva profesión hasta que se cambie de vista o se haga un refresh de la misma donde vuelve al nombre original. 

Lo ideal seria que al momento de editar si se modifican los campos y de decide cancelar, los datos originales no deben desaparecer, salvo cuando se guarden dichos cambios.

2023-03-31 14:19 UTC, AgosLizzi requested changes
Aldo. Aca van algunas observaciones
- Cuando edito el título de una profesión ya matriculada, sin dar aceptar a la acción, me "confirma" ese campo además de que me salta un error sobre la consola. Te dejo video para que veas
https://www.loom.com/share/d59e9bee464340a0a5ca2b6bb4c59e18
Me sucede de igual manera con una profesión que puedo editar. Cambio el título y sin dar aceptar, me confirma, sumado a que explota de error en la consola

2023-06-08 16:00 UTC, aldoEMatamala commented
> Al momento de editar una profesión, si elimino el nombre de la misma se rompe todo como se ve en la imagen. Las clases que generan este tipo de inconveniente son:
> 
>     * formacion-grado.html en la linea 107
> 
>     * formacion-grado-detalle.html en la linea 2
>       ![image](https://user-images.githubusercontent.com/65697028/223484436-42aee0db-95a2-43bb-a7ea-6ed633706011.png)
> 
> 
> También ocurre lo siguiente para agregar en la misma corrección:
> 
>     * Cuando edito una profesión, borro el nombre y apreto el botón cancelar, el grado editado desaparece y vuelve a arrojar múltiples errores en la consola.
>       ![image](https://user-images.githubusercontent.com/65697028/223485477-27bc4fec-26e5-4904-8d01-2fd3d197d26a.png)
> 
>     * Cuando edito una profesión, agrego otro nombre y apreto el botón cancelar, el grado editado queda con la nueva profesión hasta que se cambie de vista o se haga un refresh de la misma donde vuelve al nombre original.
> 
> 
> Lo ideal seria que al momento de editar si se modifican los campos y de decide cancelar, los datos originales no deben desaparecer, salvo cuando se guarden dichos cambios.
Hola Campe! gracias por las observaciones, corregidos errores:
-al borrar nombre
-borrar profesion
-cancelar

2023-06-08 16:02 UTC, aldoEMatamala commented
> Aldo. Aca van algunas observaciones
> 
>     * Cuando edito el título de una profesión ya matriculada, sin dar aceptar a la acción, me "confirma" ese campo además de que me salta un error sobre la consola. Te dejo video para que veas
>       https://www.loom.com/share/d59e9bee464340a0a5ca2b6bb4c59e18
>       Me sucede de igual manera con una profesión que puedo editar. Cambio el título y sin dar aceptar, me confirma, sumado a que explota de error en la consola

Hola Agos! gracias por las observaciones. Se corrigieron errores de:
- editar campos y cancelar/guardar

2023-06-08 18:59 UTC, MarianoCampetella commented
![image](https://github.com/andes/matriculaciones/assets/65697028/c8b1c17d-f9a8-4984-b549-dc68b17dd5dc)
Veo los siguentes errores (disculpa que no los haya mencionado anteriormente):
- Segun la descripcion de la tarea: "... la formación de grado se pueda editar siempre y cuando se encuentre cargada y/o con papeles verificados (true), pero no asociada a un número de matricula." Entonces se puede observar que puedo seguir editando una matricula a pesar de que tenga o no asginado un numero de matricula. 
- Cuando se borran los datos de la matricula el boton sigue habilitado aunque no realice ninguna acción. Se puede optar por dos opciones: mostrar un toast de que hay campos obligatorios sin completar o deshabilitarlo hasta que se completen todos.
- Todavía sigue figurando los errores de consola cuando borro todos los filtros y apreto el botón cancelar.

2023-06-16 15:38 UTC, aldoEMatamala commented
> ![image](https://user-images.githubusercontent.com/65697028/244477001-c8b1c17d-f9a8-4984-b549-dc68b17dd5dc.png) Veo los siguentes errores (disculpa que no los haya mencionado anteriormente):
> 
>     * Segun la descripcion de la tarea: "... la formación de grado se pueda editar siempre y cuando se encuentre cargada y/o con papeles verificados (true), pero no asociada a un número de matricula." Entonces se puede observar que puedo seguir editando una matricula a pesar de que tenga o no asginado un numero de matricula.
> 
>     * Cuando se borran los datos de la matricula el boton sigue habilitado aunque no realice ninguna acción. Se puede optar por dos opciones: mostrar un toast de que hay campos obligatorios sin completar o deshabilitarlo hasta que se completen todos.
> 
>     * Todavía sigue figurando los errores de consola cuando borro todos los filtros y apreto el botón cancelar.

Hola Campe! gracias por las observaciones, corregidos los errores mencionados. Lo único q se bloquea es la modificación de la profesión de grado

2023-06-16 15:43 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9096](http://condorpiedra.andes.gob.ar:85/9096/mochawesome.html)
CYPRESS RUN: [8246](https://dashboard.cypress.io/projects/xr7gft/runs/8246/specs)
TEST START: 2023-06-16T15:43:26.346Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-06-23 18:11 UTC, MarianoCampetella approved these changes

2023-06-23 18:11 UTC, MarianoCampetella commented on src/app/components/profesionales/formacionGrado/formacion-grado.html
> +                         [disabled]=" !formacionSelected.papelesVerificados || formacionSelected.matriculacion !== null  "
Deberia ser la condición: [disabled]=" formacionSelected.papelesVerificados || formacionSelected.matriculacion " ya que del caso contrario apenas creo una matricula no puedo editar la profesión ya que nunca va a estar habilitado dicho select.

2023-06-23 18:14 UTC, MarianoCampetella requested changes

2023-06-23 18:14 UTC, MarianoCampetella commented on src/app/components/profesionales/formacionGrado/formacion-grado.html
> +                         [disabled]=" !formacionSelected.papelesVerificados || formacionSelected.matriculacion !== null  "
Deberia ser la condición: [disabled]=" formacionSelected.papelesVerificados || formacionSelected.matriculacion " ya que del caso contrario apenas creo una matricula no puedo editar la profesión ya que nunca va a estar habilitado dicho select.

2023-06-29 13:15 UTC, aldoEMatamala commented on src/app/components/profesionales/formacionGrado/formacion-grado.html
> +                         [disabled]=" !formacionSelected.papelesVerificados || formacionSelected.matriculacion !== null  "
hola campe! como lo hablamos por slack queda solo con [disabled]= formacionSelected.matriculacion para q permita modificar la profesion al crear la formacion de grado y al verificar papeles. Saludos

2023-06-29 14:36 UTC, aldoEMatamala commented
> 



> Aldoo, solo un detalle pequeño para corregir. El resto lo veo bien!
> 
>     1. Cambiaría el mensaje del tooltip "Se guardo con éxito", para que sea un poco más informativo. Pondría algo como: "Profesión editada con éxito" o "La profesión se guardo con exito", mismo mensaje, distintas formas de escribirlo.



> Aldoo, solo un detalle pequeño para corregir. El resto lo veo bien!
> 
>     1. Cambiaría el mensaje del tooltip "Se guardo con éxito", para que sea un poco más informativo. Pondría algo como: "Profesión editada con éxito" o "La profesión se guardo con exito", mismo mensaje, distintas formas de escribirlo.
 Gracias por la revisión Agos, se modifica toast a "La profesión se guardó con éxito" y se agregan tildes en toast de otros componentes similares los cuales quedan mencionados en la descripción del PR. Saludos!

2023-06-29 18:37 UTC, MarianoCampetella approved these changes

2023-08-16 11:45 UTC, AgosLizzi approved these changes

2023-09-07 12:20 UTC, closed without merging