MAT - Unificar cargar/editar baja de matrícula
andes/matriculaciones pull request #205
Opened 2023-03-09 15:38 UTC by aldoEMatamala

### Requerimiento
* https://proyectos.andes.gob.ar/browse/MAT-123
### Funcionalidad desarrollada 

1. Baja, edición de baja  y edición de matriculación se realizan desde el mismo componente, segúnlos mockups que se realizaron.
2. Corregido bug que al dar de baja una matrícula a veces no se actualizaba la vista "motivo de baja- fecha" en sidebar

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [x] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

2023-03-31 13:50 UTC, AgosLizzi requested changes
Aldo, veo un par de detallitos. 
1. Veo un par de diferencias con respecto al mockup 
![2023-03-31](https://user-images.githubusercontent.com/72876985/229135700-f96ba9a1-f8a1-42c8-a389-015ad7d9013b.png)
![mock-04](https://user-images.githubusercontent.com/72876985/229136359-b6b889a1-67aa-43b3-a2e0-3ed5a8f61e10.jpg)
2. Cuando edito la baja de la matricula no hay ningun aviso que dicha acción se realizó satisfactoriamente o no. Te dejo video
https://www.loom.com/share/cd44372ac5924b84bb96a030f65c5d02
3. Los botones de editar estan demasiados grandes. Tal vez se podrían achicar un poco para que queden mas alineados con la caja de texto.
![2023-03-31 (4)](https://user-images.githubusercontent.com/72876985/229138538-1338ef39-7fac-464a-aa13-da44279aafc7.png)

2023-06-28 17:42 UTC, MarianoCampetella commented
Aldito, te dejo un par de observaciones extras: 
- Como los campos de motivo y fecha de baja son obligatorios, entonces no me debería habilitar la opción de guardar si al menos uno de ellos no posee ningún texto.
- Al momento de guardar la edición de la baja de una matricula, estaría bueno agregar un toast indicándole al usuario que la acción se hizo de forma correcta.
![image](https://github.com/andes/matriculaciones/assets/65697028/374c8436-1cd4-4dd5-a5da-b3a8f91ae8c8)

2023-06-28 17:44 UTC, MarianoCampetella commented
En base al comentario anterior si borro los campos y le doy al boton cancelar, ocurre que despues se me pierde la informacion y se visualiza de la siguiente manera. 
![image](https://github.com/andes/matriculaciones/assets/65697028/ed764d64-4f28-4645-8fe1-0924d1dc1813)
Lo ideal seria que si sucede eso, la información siga siendo la misma hasta el momento que se guarden los nuevos datos.

2023-06-28 17:54 UTC, MarianoCampetella requested changes

2023-06-28 17:54 UTC, MarianoCampetella commented on src/app/components/profesionales/formacionGrado/formacion-grado-detalle.html
> +  <div *ngIf='formacion.matriculacion && formacion.matriculado === true && campoBaja  '>
Dejar la conficion como *ngIf='formacion.matriculacion && formacion.matriculado && campoBaja'

2023-06-28 17:54 UTC, MarianoCampetella commented on src/app/components/profesionales/formacionGrado/formacion-grado-detalle.html
> +    <div class="row">
Si bien entre funciones o métodos distintos esta bueno dejar algún que otro espacio en blanco para poder diferenciarlos, pero en estos casos no es necesario tener varios espacios en blanco ya que aumentan la cantidad de lineas de código. Este mismo criterio aplicarlo en todos los lugares que ocurran lo mismo!

2023-06-28 17:54 UTC, MarianoCampetella commented on src/app/components/profesionales/formacionGrado/formacion-grado.html
> +                         [disabled]=" !formacionSelected.papelesVerificados || formacionSelected.matriculacion !== null  ">
El disabled lo podemos dejar de la forma:  !formacionSelected.papelesVerificados || formacionSelected.matriculacion

2023-08-03 13:48 UTC, aldoEMatamala commented
> En base al comentario anterior si borro los campos y le doy al boton cancelar, ocurre que despues se me pierde la informacion y se visualiza de la siguiente manera. ![image](https://user-images.githubusercontent.com/65697028/249567902-ed764d64-4f28-4645-8fe1-0924d1dc1813.png) Lo ideal seria que si sucede eso, la información siga siendo la misma hasta el momento que se guarden los nuevos datos.

correjido error que venia de antes cuando se cancela una edición, gracias!

2023-08-03 13:54 UTC, aldoEMatamala commented on src/app/components/profesionales/formacionGrado/formacion-grado-detalle.html
> +    <div class="row">
correjido gracias !

2023-08-03 13:54 UTC, aldoEMatamala commented on src/app/components/profesionales/formacionGrado/formacion-grado.html
> +                         [disabled]=" !formacionSelected.papelesVerificados || formacionSelected.matriculacion !== null  ">
correjido gracias !

2023-08-03 14:34 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9340](http://condorpiedra.andes.gob.ar:85/9340/mochawesome.html)
CYPRESS RUN: [8480](https://dashboard.cypress.io/projects/xr7gft/runs/8480/specs)
TEST START: 2023-08-03T14:33:48.819Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-03 16:11 UTC, MarianoCampetella approved these changes

2023-08-03 17:53 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9349](http://condorpiedra.andes.gob.ar:85/9349/mochawesome.html)
CYPRESS RUN: [8488](https://dashboard.cypress.io/projects/xr7gft/runs/8488/specs)
TEST START: 2023-08-03T17:52:24.654Z
TOTAL: 310
SUCCESS: 293
FAIL: 15
SKIPPED: 2
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-08-03 18:45 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9350](http://condorpiedra.andes.gob.ar:85/9350/mochawesome.html)
CYPRESS RUN: [8489](https://dashboard.cypress.io/projects/xr7gft/runs/8489/specs)
TEST START: 2023-08-03T18:44:00.926Z
TOTAL: 202
SUCCESS: 154
FAIL: 47
SKIPPED: 1
:warning::warning::warning::warning:
Hay archivos que no corrieron. Vuelva a intentar.

2023-08-04 12:18 UTC, silviroa commented
USUARIO: amatamala  
BUILD NUMBER: [9352](http://condorpiedra.andes.gob.ar:85/9352/mochawesome.html)
CYPRESS RUN: [8491](https://dashboard.cypress.io/projects/xr7gft/runs/8491/specs)
TEST START: 2023-08-04T12:18:18.381Z
TOTAL: 403
SUCCESS: 401
FAIL: 0
SKIPPED: 2

2023-08-07 14:51 UTC, AgosLizzi approved these changes

2023-09-05 11:51 UTC, merged