MAT - Quitar badge "Año de gracia" en profesiones de grado
andes/matriculaciones pull request #207
Opened 2023-04-25 16:10 UTC by aldoEMatamala

### Requerimiento
* URL de la User Story, referencia al issue (#1111) o breve descripcion del requerimiento
https://proyectos.andes.gob.ar/browse/MAT-136
### Funcionalidad desarrollada 

1. Se retira badge " Año de gracia" y se reemplaza por "Matricula Vencida" en profesiones de grado.

### UserStory llegó a completarse

- [ ] Si
- [x] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [x] No

### Requiere actualizaciones en la API

- [ ] Si
- [x] No

2023-04-26 13:16 UTC, MCele requested changes

2023-04-26 13:16 UTC, MCele commented on src/app/components/profesionales/formacionGrado/formacion-grado.html
> +          {{verificarFecha(i)?' Matricula Vencida':'Año de graciaFG'}}
evitemos código comentado, de echo aprovecharía para borrar el que ya estaba de antes

2023-04-26 13:17 UTC, MCele commented on src/app/components/profesionales/listar-profesionales.html
> +-->
idem comentario anterior

2023-04-26 14:43 UTC, aldoEMatamala commented on src/app/components/profesionales/formacionGrado/formacion-grado.html
> +          {{verificarFecha(i)?' Matricula Vencida':'Año de graciaFG'}}
Comentarios retirados, se me escaparon

2023-04-27 12:31 UTC, MCele approved these changes

2023-04-27 13:41 UTC, silviroa commented
USUARIO: mcampetella  
BUILD NUMBER: [8782](http://condorpiedra.andes.gob.ar:85/8782/mochawesome.html)
CYPRESS RUN: [7953](https://dashboard.cypress.io/projects/xr7gft/runs/7953/specs)
TEST START: 2023-04-27T13:41:28.683Z
TOTAL: 406
SUCCESS: 404
FAIL: 0
SKIPPED: 2

2023-04-27 15:01 UTC, merged