MAT - Implementar mockup guia profesional
andes/matriculaciones pull request #216
Opened 2024-04-10 16:26 UTC by aldoEMatamala

### Requerimiento
* URL de la User Story, referencia al issue (#1111) o breve descripcion del requerimiento
https://proyectos.andes.gob.ar/browse/MAT-164
### Funcionalidad desarrollada 

1. Se agrupan formaciones de grado por profesional.
2. Se toma en cuenta la adaptabilidad a dispositivos moviles.

### UserStory llegó a completarse

- [ ] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [ ] No

### Requiere actualizaciones en la API

- [ ] Si
- [ ] No

2024-05-30 12:09 UTC, AgosLizzi approved these changes

2024-06-04 13:06 UTC, aldoEMatamala commented
![imagen](https://github.com/andes/matriculaciones/assets/123381977/ec0f2c01-9b79-46d6-b27c-65d117a4bfa1)

2024-06-11 12:44 UTC, MCele requested changes
Aldo esta hermosa la nueva visualización!
Lo que si veo que en algunos casos está tirando un error la app, que se puede ver en la consola del navegador
![image](https://github.com/andes/matriculaciones/assets/19591224/91c40a9c-ca24-4d74-bf99-b59a49e7571b)

2024-06-13 12:31 UTC, aldoEMatamala commented
> Aldo quedó hermosa la nueva visualización! Lo que si veo que en algunos casos está tirando un error la app, que se puede ver en la consola del navegador ![image](https://private-user-images.githubusercontent.com/19591224/338587064-91c40a9c-ca24-4d74-bf99-b59a49e7571b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODE4MzIsIm5iZiI6MTcxODI4MTUzMiwicGF0aCI6Ii8xOTU5MTIyNC8zMzg1ODcwNjQtOTFjNDBhOWMtY2EyNC00ZDc0LWJmOTktYjU5YTQ5ZTc1NzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEyMjUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNTc5NGU2NTU2MWIzNDMwODkxYjQ2ZGFhNmQwNzU5NDdmNjg5MTY2MWEzZjIwNDU5NDlkZWQwMTBkZGE5YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fEX1Mjnt8yMAxgMTvXsi21A0tEQeuRHU48eQCuWd5B8)

hola cele, gracias por la revisión!
Queda corregido el fallo cuando el profesional no tenia profesiones de grado cargadas.
![imagen](https://github.com/andes/matriculaciones/assets/123381977/6aa1baea-26d1-470a-b2f7-997dbdb7bcbc)
Queda resolver si en ése caso mostramos el "sin resultados" como en la imagen ó si directamente no mostramos al profesional.

2024-06-13 18:39 UTC, aldoEMatamala commented
> > Aldo quedó hermosa la nueva visualización! Lo que si veo que en algunos casos está tirando un error la app, que se puede ver en la consola del navegador ![image](https://private-user-images.githubusercontent.com/19591224/338587064-91c40a9c-ca24-4d74-bf99-b59a49e7571b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyODE4MzIsIm5iZiI6MTcxODI4MTUzMiwicGF0aCI6Ii8xOTU5MTIyNC8zMzg1ODcwNjQtOTFjNDBhOWMtY2EyNC00ZDc0LWJmOTktYjU5YTQ5ZTc1NzFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEyMjUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNTc5NGU2NTU2MWIzNDMwODkxYjQ2ZGFhNmQwNzU5NDdmNjg5MTY2MWEzZjIwNDU5NDlkZWQwMTBkZGE5YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fEX1Mjnt8yMAxgMTvXsi21A0tEQeuRHU48eQCuWd5B8)
> 
> hola cele, gracias por la revisión! Queda corregido el fallo cuando el profesional no tenia profesiones de grado cargadas. ![imagen](https://private-user-images.githubusercontent.com/123381977/339357541-6aa1baea-26d1-470a-b2f7-997dbdb7bcbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMDM4MjcsIm5iZiI6MTcxODMwMzUyNywicGF0aCI6Ii8xMjMzODE5NzcvMzM5MzU3NTQxLTZhYTFiYWVhLTI2ZDEtNDcwYS1iMmY3LTk5N2RiZGI3YmNiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxODMyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWUwZmY1M2UzNDZmODZlYTIzODUwZjBhMGZkYjU2YzcxMzJlMTkxYTRmOWEyOGFkZGM0OGIyNTMzYzhkYjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OwFyI9vuHTDiYMwvOM0aqCJOSf52YZ7mlKLvPmLYzp8) Queda resolver si en ése caso mostramos el "sin resultados" como en la imagen ó si directamente no mostramos al profesional.

Como lo hablado personalmente, se opta por no listar a un profesional sin profesiones de grado que cumplan las condiciones.

2024-08-13 12:07 UTC, aldoEMatamala commented
> Compa estaria bien la representacion visual, lo unico es que veo este temita. ![image](https://private-user-images.githubusercontent.com/45831788/353521938-51bc4124-6508-42ca-9351-2dd604ffca4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTA4NDMsIm5iZiI6MTcyMzU1MDU0MywicGF0aCI6Ii80NTgzMTc4OC8zNTM1MjE5MzgtNTFiYzQxMjQtNjUwOC00MmNhLTkzNTEtMmRkNjA0ZmZjYTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEyMDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0OTkwNDk3YWYzNjY3MjMwYzc2MWM1MzQwNTdjZWNiYmVlYmQxNTUxMmIzMGU5MzgxNzEyY2FlYWY4Y2M2MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DoQejpo_Fn5a093vH7uV-CQgR8T0OuzwIoy8i2uJ78Q)

Buenas fabio! gracias por la revision, me habia faltado subir la ultima actualizacion donde se corregia lo que mencionas. Gracias!
![imagen](https://github.com/user-attachments/assets/66b57bc9-3b0a-4351-b88e-a5380dfc7d3e)

2024-08-13 18:26 UTC, aldoEMatamala commented
![imagen](https://github.com/user-attachments/assets/ab8377a4-1745-44bb-ad4e-6d09fbe1f4c0)

2024-08-15 15:51 UTC, merged