MAT - Validar profesional con Renaper
andes/matriculaciones pull request #219
Opened 2024-09-12 18:14 UTC by MarianoCampetella

### Requerimiento
https://proyectos.andes.gob.ar/browse/MAT-174

### Funcionalidad desarrollada 
1. Se validan los profesionales al momento de crearse o editarse.
2. Se agregan los labels VALIDADO - NO VALIDADO según corresponda

### UserStory llegó a completarse

- [X] Si
- [ ] No
- [ ] No corresponde

### Requiere actualizaciones en la base de datos

- [ ] Si
- [X] No

### Requiere actualizaciones en la API

- [ ] Si
- [X] No

2024-11-01 16:17 UTC, AgosLizzi approved these changes

2024-11-05 13:54 UTC, Fabio-Ramirez approved these changes

2025-02-24 19:08 UTC, negro89 requested changes

2025-03-10 15:57 UTC, MarianoCampetella commented on src/app/components/profesionales/profesional.component.ts
> +                    if (this.profesional.nacionalidad.nombre !== 'Argentina' || !responseActualizar[0].error || responseActualizar[0].menssage) {
Corregido!! Estoy atento a nuevos cambios!

2025-03-11 18:14 UTC, negro89 requested changes
Campe, algunas observaciones mas sobre el flujo de registro de nueva matricula. El otro esta ok

2025-03-11 18:14 UTC, negro89 commented on src/app/components/profesionales/profesional.component.ts
> +                    if (!profesionalError.error || profesionalError.menssage) {
_profesionalError.menssage_ debería estar negado, ya que si la respuesta esta ok esto debería ser _undefined_

2025-03-11 18:14 UTC, negro89 commented on src/app/components/profesionales/profesional.component.ts
> +                        if (this.profesional.nacionalidad.nombre === 'Argentina') {
La nacionalidad no importa, si tiene dni argentino RENAPER lo valida

2025-03-11 18:14 UTC, negro89 commented on src/app/components/profesionales/profesional.component.ts
>                  switchMap(responseActualizar => {
antes de este _switchMap_ agregaría un _catchError_ en caso de timeout (renaper caido). En este caso re-adaptar el flujo que sigue para que no impida registrar al nuevo profesional

2025-03-28 12:33 UTC, MarianoCampetella commented on src/app/components/profesionales/profesional.component.ts
> +                        if (this.profesional.nacionalidad.nombre === 'Argentina') {
Corregido, se sacó el if de nacionalidad.

2025-04-10 18:20 UTC, merged